from . import X

PAGE = {
    'slug': 'partners.html',
    'title': X('Technology Partners', 'Технологические партнёры', 'Texnologik hamkorlar'),
    'image': 'radio-detail.webp',
    'hero': {
        'title': X('Global Technology. Local Integration.', 'Мировые технологии. Местная интеграция.', 'Global texnologiyalar. Mahalliy integratsiya.'),
        'lead': X('Strong technology partnerships are fundamental to the S3 approach.',
                  'Прочные технологические партнёрства — основа подхода S3.',
                  'Mustahkam texnologik hamkorliklar S3 yondashuvining asosidir.'),
    },
    'blocks': [
        ('continuation', {'items': [
            ('p', X('Modern mission-critical solutions often require technologies and expertise from multiple specialized organizations. S3 works with established international manufacturers and experienced integration partners to bring advanced technologies, specialist knowledge, and proven solutions to our customers in Uzbekistan.',
                    'Современные решения для критически важных задач часто требуют технологий и экспертизы сразу нескольких специализированных организаций. S3 работает с признанными международными производителями и опытными партнёрами по интеграции, чтобы предлагать заказчикам в Узбекистане передовые технологии, специальные знания и проверенные решения.',
                    'Zamonaviy o‘ta muhim yechimlar ko‘pincha bir nechta ixtisoslashgan tashkilotlarning texnologiyalari va ekspertizasini talab qiladi. S3 O‘zbekistondagi buyurtmachilariga ilg‘or texnologiyalar, ixtisoslashgan bilimlar va sinovdan o‘tgan yechimlarni yetkazish uchun tan olingan xalqaro ishlab chiqaruvchilar va tajribali integratsiya hamkorlari bilan ishlaydi.')),
            ('p', X('Our role is to connect this international expertise with local requirements, systems integration, training, knowledge transfer, and lifecycle support.',
                    'Наша роль — соединять эту международную экспертизу с местными требованиями, системной интеграцией, обучением, передачей знаний и поддержкой жизненного цикла.',
                    'Bizning vazifamiz — bu xalqaro ekspertizani mahalliy talablar, tizim integratsiyasi, o‘qitish, bilim uzatish va hayotiy sikl davomida qo‘llab-quvvatlash bilan bog‘lash.')),
            ('p', X('The result is more than access to technology.', 'Результат — это больше, чем доступ к технологиям.', 'Natija — texnologiyalardan foydalanish imkoniyatidan ham ko‘proq.')),
            ('emphasis', X('It is a partnership model designed to transform advanced technologies into sustainable operational capabilities.',
                           'Это модель партнёрства, созданная для того, чтобы превращать передовые технологии в устойчивые операционные возможности.',
                           'Bu ilg‘or texnologiyalarni barqaror operatsion imkoniyatlarga aylantirishga mo‘ljallangan hamkorlik modelidir.')),
        ]}),
        ('prose', {'title': X('Our Partnership Approach', 'Наш подход к партнёрству', 'Hamkorlikka yondashuvimiz'), 'soft': True, 'items': [
            ('p', X('S3 develops partnerships with technology manufacturers and organizations whose products, expertise, and capabilities complement our systems integration portfolio.',
                    'S3 развивает партнёрство с производителями технологий и организациями, чьи продукты, экспертиза и возможности дополняют наш портфель в области системной интеграции.',
                    'S3 mahsulotlari, ekspertizasi va imkoniyatlari tizim integratsiyasi portfelimizni to‘ldiradigan texnologiya ishlab chiqaruvchilari va tashkilotlar bilan hamkorlikni rivojlantiradi.')),
            ('p', X('When evaluating technologies and potential partners, we consider factors including:',
                    'Оценивая технологии и потенциальных партнёров, мы учитываем, в частности:',
                    'Texnologiyalar va potentsial hamkorlarni baholashda quyidagi omillarni hisobga olamiz:')),
            ('list', [
                X('Proven technology and operational reliability', 'Проверенность технологий и эксплуатационную надёжность', 'Sinovdan o‘tgan texnologiya va operatsion ishonchlilik'),
                X('Security and resilience', 'Безопасность и устойчивость', 'Xavfsizlik va barqarorlik'),
                X('Interoperability', 'Совместимость', 'O‘zaro moslik'),
                X('Technical performance', 'Технические характеристики', 'Texnik ko‘rsatkichlar'),
                X('Integration capabilities', 'Возможности интеграции', 'Integratsiya imkoniyatlari'),
                X('Product and technology lifecycle', 'Жизненный цикл продукта и технологии', 'Mahsulot va texnologiyaning hayotiy sikli'),
                X('Availability of manufacturer expertise', 'Доступность экспертизы производителя', 'Ishlab chiqaruvchi ekspertizasining mavjudligi'),
                X('Training and knowledge-transfer capabilities', 'Возможности обучения и передачи знаний', 'O‘qitish va bilim uzatish imkoniyatlari'),
                X('Technical and lifecycle support', 'Техническую поддержку и поддержку жизненного цикла', 'Texnik yordam va hayotiy sikl davomida qo‘llab-quvvatlash'),
                X('Compatibility with customer requirements and existing environments', 'Соответствие требованиям заказчика и существующей среде', 'Buyurtmachi talablari va mavjud muhitga moslik'),
            ]),
            ('p', X('Our objective is not to build the largest possible list of vendors.',
                    'Наша цель — не собрать как можно более длинный список поставщиков.',
                    'Maqsadimiz iloji boricha uzun yetkazib beruvchilar ro‘yxatini tuzish emas.')),
            ('p', X('We aim to develop a strong technology ecosystem that allows S3 to select and integrate appropriate technologies according to each customer\'s operational and technical requirements.',
                    'Мы стремимся создать сильную технологическую экосистему, которая позволяет S3 выбирать и интегрировать подходящие технологии с учётом операционных и технических требований каждого заказчика.',
                    'Biz S3 ga har bir buyurtmachining operatsion va texnik talablariga muvofiq mos texnologiyalarni tanlash va integratsiya qilish imkonini beradigan kuchli texnologik ekotizimni rivojlantirishga intilamiz.')),
        ]}),
        ('partner', {
            'title': X('L3Harris Technologies', 'L3Harris Technologies', 'L3Harris Technologies'),
            'subtitle': X('Combat-Proven Technology for Mission-Critical Operations', 'Проверенные в боевых условиях технологии для критически важных операций', 'O‘ta muhim operatsiyalar uchun jangovar sharoitda sinovdan o‘tgan texnologiyalar'),
            'logo': 'l3harris-logo.svg',
            'items': [
                ('p', X('L3Harris Technologies is a key technology partner supporting S3\'s mission to provide advanced solutions to government and defense customers.',
                        'L3Harris Technologies — ключевой технологический партнёр, поддерживающий миссию S3 по предоставлению передовых решений государственным и оборонным заказчикам.',
                        'L3Harris Technologies — davlat va mudofaa sohasidagi buyurtmachilarga ilg‘or yechimlarni taqdim etish bo‘yicha S3 missiyasini qo‘llab-quvvatlaydigan asosiy texnologik hamkor.')),
                ('p', X('L3Harris provides technologies across mission-critical areas including secure tactical communications, resilient communications and networks, Command and Control (C2), ISR, and integrated mission systems.',
                        'L3Harris предлагает технологии в критически важных областях: защищённая тактическая связь, устойчивые системы связи и сети, командование и управление (C2), ISR и интегрированные системы для выполнения задач.',
                        'L3Harris o‘ta muhim sohalarda texnologiyalar taqdim etadi: himoyalangan taktik aloqa, barqaror aloqa va tarmoqlar, qo‘mondonlik va boshqaruv (C2), ISR hamda integratsiyalashgan vazifa tizimlari.')),
                ('p', X('Its portfolio enables secure connectivity and information exchange across users, networks, platforms, sensors, and command-and-control environments.',
                        'Её портфель обеспечивает защищённую связь и обмен информацией между пользователями, сетями, платформами, датчиками и средой командования и управления.',
                        'Uning portfeli foydalanuvchilar, tarmoqlar, platformalar, sensorlar hamda qo‘mondonlik va boshqaruv muhiti o‘rtasida himoyalangan aloqa va axborot almashinuvini ta’minlaydi.')),
                ('p', X('For S3, cooperation with L3Harris provides access not only to advanced technology but also to specialist product knowledge, engineering expertise, training resources, and technical support.',
                        'Для S3 сотрудничество с L3Harris — это доступ не только к передовым технологиям, но и к специальным знаниям о продуктах, инженерной экспертизе, учебным ресурсам и технической поддержке.',
                        'S3 uchun L3Harris bilan hamkorlik nafaqat ilg‘or texnologiyalarga, balki mahsulotlar bo‘yicha ixtisoslashgan bilimlar, muhandislik ekspertizasi, o‘quv resurslari va texnik yordamga ham yo‘l ochadi.')),
                ('p', X('S3 complements these capabilities through local customer engagement, systems integration, deployment support, training, knowledge transfer, and lifecycle services in Uzbekistan.',
                        'S3 дополняет эти возможности местным взаимодействием с заказчиками, системной интеграцией, поддержкой развёртывания, обучением, передачей знаний и услугами жизненного цикла в Узбекистане.',
                        'S3 bu imkoniyatlarni O‘zbekistonda buyurtmachilar bilan mahalliy hamkorlik, tizim integratsiyasi, joriy etishni qo‘llab-quvvatlash, o‘qitish, bilim uzatish va hayotiy sikl xizmatlari bilan to‘ldiradi.')),
                ('p', X('Together, these capabilities support our approach:', 'Вместе эти возможности поддерживают наш подход:', 'Birgalikda bu imkoniyatlar yondashuvimizni qo‘llab-quvvatlaydi:')),
                ('flow', [
                    X('Global Technology', 'Мировые технологии', 'Global texnologiyalar'),
                    X('Local Integration', 'Местная интеграция', 'Mahalliy integratsiya'),
                    X('Operational Capability', 'Операционные возможности', 'Operatsion imkoniyat'),
                ]),
                ('h3', X('From Communications to Integrated Systems', 'От связи — к интегрированным системам', 'Aloqadan — integratsiyalashgan tizimlargacha')),
                ('p', X('Our cooperation with L3Harris supports S3 capabilities in areas such as:',
                        'Сотрудничество с L3Harris поддерживает возможности S3 в таких областях, как:',
                        'L3Harris bilan hamkorligimiz S3 imkoniyatlarini quyidagi sohalarda qo‘llab-quvvatlaydi:')),
                ('list', [
                    X('Secure tactical radio communications', 'Защищённая тактическая радиосвязь', 'Himoyalangan taktik radioaloqa'),
                    X('Tactical networking', 'Тактические сети', 'Taktik tarmoqlar'),
                    X('Command and Control (C2)', 'Командование и управление (C2)', 'Qo‘mondonlik va boshqaruv (C2)'),
                    X('Situational awareness', 'Ситуационная осведомлённость', 'Vaziyatdan xabardorlik'),
                    X('Secure voice and data exchange', 'Защищённый обмен голосом и данными', 'Himoyalangan ovoz va ma’lumot almashinuvi'),
                    X('Communications and network planning', 'Планирование связи и сетей', 'Aloqa va tarmoqlarni rejalashtirish'),
                    X('Integrated tactical communication systems', 'Интегрированные тактические системы связи', 'Integratsiyalashgan taktik aloqa tizimlari'),
                    X('System interoperability', 'Совместимость систем', 'Tizimlarning o‘zaro mosligi'),
                    X('Training and knowledge transfer', 'Обучение и передача знаний', 'O‘qitish va bilim uzatish'),
                    X('Technical and lifecycle support', 'Техническая поддержка и поддержка жизненного цикла', 'Texnik yordam va hayotiy sikl davomida qo‘llab-quvvatlash'),
                ]),
                ('p', X('The objective is not simply to provide individual L3Harris products.',
                        'Цель — не просто поставлять отдельные продукты L3Harris.',
                        'Maqsad shunchaki alohida L3Harris mahsulotlarini yetkazib berish emas.')),
                ('p', X('S3 works to integrate these technologies into complete solutions designed around customer requirements and, where technically feasible, to connect new capabilities with systems and infrastructure already in operation.',
                        'S3 интегрирует эти технологии в законченные решения, построенные вокруг требований заказчика, и там, где это технически возможно, связывает новые возможности с уже эксплуатируемыми системами и инфраструктурой.',
                        'S3 bu texnologiyalarni buyurtmachi talablari asosida yaratilgan yaxlit yechimlarga integratsiya qiladi va texnik jihatdan mumkin bo‘lgan hollarda yangi imkoniyatlarni allaqachon foydalanilayotgan tizimlar va infratuzilma bilan bog‘laydi.')),
                ('p', X('This reflects one of our core integration principles:', 'Это отражает один из ключевых принципов нашей интеграции:', 'Bu integratsiyadagi asosiy tamoyillarimizdan birini aks ettiradi:')),
                ('emphasis', X('Modernization Without Starting From Zero.', 'Модернизация без начала с нуля.', 'Noldan boshlamasdan modernizatsiya.')),
                ('buttons', [(X('Visit L3Harris Technologies', 'Сайт L3Harris Technologies', 'L3Harris Technologies saytiga o‘tish'), 'https://www.l3harris.com/', 'text-link')]),
            ],
        }),
        ('partner', {
            'title': X('Digital Technologies (DTECH)', 'Digital Technologies (DTECH)', 'Digital Technologies (DTECH)'),
            'subtitle': X('Integration Experience. Technical Expertise. Regional Cooperation.', 'Опыт интеграции. Техническая экспертиза. Региональное сотрудничество.', 'Integratsiya tajribasi. Texnik ekspertiza. Mintaqaviy hamkorlik.'),
            'logo': 'dtech-logo-horizontal.svg',
            'light': True,
            'soft': True,
            'items': [
                ('p', X('Digital Technologies (DTECH) is an experienced technology and systems integration company based in Georgia and an important partner in S3\'s development and delivery of mission-critical solutions.',
                        'Digital Technologies (DTECH) — опытная технологическая компания и системный интегратор из Грузии, важный партнёр S3 в разработке и поставке решений для критически важных задач.',
                        'Digital Technologies (DTECH) — Gruziyada joylashgan tajribali texnologiya va tizim integratsiyasi kompaniyasi hamda o‘ta muhim yechimlarni ishlab chiqish va yetkazib berishda S3 ning muhim hamkori.')),
                ('p', X('DTECH brings extensive experience in military technologies, professional radio communications, networking solutions, systems integration, training, and technical support.',
                        'DTECH обладает обширным опытом в области военных технологий, профессиональной радиосвязи, сетевых решений, системной интеграции, обучения и технической поддержки.',
                        'DTECH harbiy texnologiyalar, professional radioaloqa, tarmoq yechimlari, tizim integratsiyasi, o‘qitish va texnik yordam sohalarida katta tajribaga ega.')),
                ('p', X('Its team includes specialists with expertise across tactical communications, networking, integration, training, and technical assistance.',
                        'В её команду входят специалисты по тактической связи, сетям, интеграции, обучению и технической помощи.',
                        'Uning jamoasida taktik aloqa, tarmoqlar, integratsiya, o‘qitish va texnik yordam bo‘yicha mutaxassislar bor.')),
                ('p', X('Cooperation between S3 and DTECH allows us to combine local presence in Uzbekistan with additional regional integration experience and specialist technical resources.',
                        'Сотрудничество S3 и DTECH позволяет сочетать местное присутствие в Узбекистане с дополнительным региональным опытом интеграции и специализированными техническими ресурсами.',
                        'S3 va DTECH hamkorligi O‘zbekistondagi mahalliy vakillikni qo‘shimcha mintaqaviy integratsiya tajribasi va ixtisoslashgan texnik resurslar bilan uyg‘unlashtirish imkonini beradi.')),
                ('h3', X('Working Together', 'Совместная работа', 'Birgalikda ishlash')),
                ('p', X('S3 and DTECH cooperate across areas including:', 'S3 и DTECH сотрудничают в таких областях, как:', 'S3 va DTECH quyidagi sohalarda hamkorlik qiladi:')),
                ('list', [
                    X('Solution development', 'Разработка решений', 'Yechimlarni ishlab chiqish'),
                    X('Systems integration', 'Системная интеграция', 'Tizim integratsiyasi'),
                    X('Tactical communications', 'Тактическая связь', 'Taktik aloqa'),
                    X('Network solutions', 'Сетевые решения', 'Tarmoq yechimlari'),
                    X('Technical consultancy', 'Технический консалтинг', 'Texnik maslahat'),
                    X('Deployment and configuration', 'Развёртывание и настройка', 'Joriy etish va sozlash'),
                    X('Customer training', 'Обучение заказчиков', 'Buyurtmachilarni o‘qitish'),
                    X('Train-the-Trainer programs', 'Программы подготовки инструкторов', 'Trenerlarni tayyorlash dasturlari'),
                    X('Technical assistance', 'Техническая помощь', 'Texnik yordam'),
                    X('Troubleshooting', 'Устранение неисправностей', 'Nosozliklarni bartaraf etish'),
                    X('Knowledge transfer', 'Передача знаний', 'Bilim uzatish'),
                    X('Lifecycle support', 'Поддержка жизненного цикла', 'Hayotiy sikl davomida qo‘llab-quvvatlash'),
                ]),
                ('p', X('This cooperation also provides S3 with access to DTECH\'s broader technical experience and established relationships with international technology manufacturers.',
                        'Это сотрудничество также открывает S3 доступ к более широкому техническому опыту DTECH и её налаженным связям с международными производителями технологий.',
                        'Bu hamkorlik S3 ga DTECH ning kengroq texnik tajribasi va xalqaro texnologiya ishlab chiqaruvchilari bilan yo‘lga qo‘yilgan aloqalaridan foydalanish imkonini ham beradi.')),
                ('p', X('Together, our teams can bring complementary expertise to complex customer requirements while maintaining strong local engagement through S3.',
                        'Вместе наши команды могут предложить взаимодополняющую экспертизу для сложных задач заказчика, сохраняя тесное местное взаимодействие через S3.',
                        'Birgalikda jamoalarimiz murakkab buyurtmachi talablariga bir-birini to‘ldiruvchi ekspertizani taqdim eta oladi va S3 orqali mustahkam mahalliy hamkorlikni saqlaydi.')),
                ('emphasis', X('International Experience. Regional Expertise. Local Support.', 'Международный опыт. Региональная экспертиза. Местная поддержка.', 'Xalqaro tajriba. Mintaqaviy ekspertiza. Mahalliy qo‘llab-quvvatlash.')),
                ('buttons', [(X('Visit DTECH', 'Сайт DTECH', 'DTECH saytiga o‘tish'), 'https://www.dtech.ge/en/', 'text-link')]),
            ],
        }),
        ('prose', {'title': X('Expanding Our Technology Ecosystem', 'Расширяем технологическую экосистему', 'Texnologik ekotizimimizni kengaytiramiz'),
                   'subtitle': X('Building Partnerships for Future Capabilities', 'Партнёрства для будущих возможностей', 'Kelajakdagi imkoniyatlar uchun hamkorliklar'), 'items': [
            ('emphasis', X('S3 continues to expand its technology portfolio.', 'S3 продолжает расширять свой технологический портфель.', 'S3 o‘z texnologik portfelini kengaytirishda davom etmoqda.')),
            ('p', X('We are currently engaged in discussions with additional established international technology manufacturers and solution providers whose capabilities can complement our existing portfolio and support the evolving requirements of our customers.',
                    'Сейчас мы ведём переговоры с другими признанными международными производителями технологий и поставщиками решений, чьи возможности могут дополнить наш портфель и отвечать меняющимся требованиям заказчиков.',
                    'Hozirda biz imkoniyatlari mavjud portfelimizni to‘ldirishi va buyurtmachilarimizning o‘zgaruvchan talablarini qo‘llab-quvvatlashi mumkin bo‘lgan boshqa tan olingan xalqaro texnologiya ishlab chiqaruvchilari va yechim yetkazib beruvchilari bilan muzokaralar olib bormoqdamiz.')),
            ('p', X('This approach allows us to continuously expand our capabilities while remaining selective about the technologies and organizations we represent and integrate.',
                    'Такой подход позволяет нам постоянно расширять возможности, оставаясь избирательными в выборе технологий и организаций, которые мы представляем и интегрируем.',
                    'Bu yondashuv biz vakillik qiladigan va integratsiya qiladigan texnologiyalar hamda tashkilotlarni tanlashda talabchan bo‘lib qolgan holda imkoniyatlarimizni doimiy kengaytirib borish imkonini beradi.')),
        ]}),
    ],
}
