from . import X, BRAND_STATEMENT, SYSTEMS_INTEGRATION

AREAS = [
    {
        'id': 'secure-tactical-communications',
        'title': X('Secure Tactical Communications', 'Защищённая тактическая связь', 'Himoyalangan taktik aloqa'),
        'subtitle': X('Reliable Communications When They Matter Most', 'Надёжная связь, когда она важнее всего', 'Eng zarur paytda ishonchli aloqa'),
        'items': [
            ('p', X('Secure and dependable communications are fundamental to effective operations.',
                    'Защищённая и надёжная связь — основа эффективных операций.',
                    'Himoyalangan va ishonchli aloqa samarali operatsiyalarning asosidir.')),
            ('p', X('S3 provides secure tactical radio communication solutions supporting voice, data, and information exchange across individual users, mobile teams, vehicles, command posts, and wider operational networks.',
                    'S3 предоставляет решения защищённой тактической радиосвязи для передачи голоса, данных и обмена информацией между отдельными пользователями, мобильными группами, транспортными средствами, командными пунктами и более широкими операционными сетями.',
                    'S3 alohida foydalanuvchilar, mobil guruhlar, transport vositalari, qo‘mondonlik punktlari va kengroq operatsion tarmoqlar o‘rtasida ovoz, ma’lumot va axborot almashinuvini ta’minlaydigan himoyalangan taktik radioaloqa yechimlarini taqdim etadi.')),
            ('p', X('Working with combat-proven technologies from our international partners, we can develop communication solutions for different operational levels and environments.',
                    'Используя проверенные в боевых условиях технологии наших международных партнёров, мы можем создавать решения связи для разных операционных уровней и условий.',
                    'Xalqaro hamkorlarimizning jangovar sharoitda sinovdan o‘tgan texnologiyalari asosida turli operatsion darajalar va sharoitlar uchun aloqa yechimlarini ishlab chiqa olamiz.')),
            ('p', X('Our capabilities include:', 'Наши возможности включают:', 'Imkoniyatlarimiz quyidagilarni o‘z ichiga oladi:')),
            ('list', [
                X('Tactical radio communication systems', 'Системы тактической радиосвязи', 'Taktik radioaloqa tizimlari'),
                X('Secure voice and data communications', 'Защищённая передача голоса и данных', 'Himoyalangan ovozli aloqa va ma’lumot uzatish'),
                X('Handheld, manpack, mobile, and fixed radio solutions', 'Носимые, ранцевые, мобильные и стационарные радиостанции', 'Qo‘l, yelkada olib yuriladigan, mobil va statsionar radio yechimlari'),
                X('Tactical radio networks', 'Тактические радиосети', 'Taktik radiotarmoqlar'),
                X('Radio network planning and configuration', 'Планирование и настройка радиосетей', 'Radiotarmoqlarni rejalashtirish va sozlash'),
                X('Integration of radio communications with C2 and other operational systems', 'Интеграция радиосвязи с системами C2 и другими операционными системами', 'Radioaloqani C2 va boshqa operatsion tizimlar bilan integratsiya qilish'),
                X('Communication system deployment and configuration', 'Развёртывание и настройка систем связи', 'Aloqa tizimlarini joriy etish va sozlash'),
                X('Training, technical support, and lifecycle services', 'Обучение, техническая поддержка и услуги на протяжении жизненного цикла', 'O‘qitish, texnik yordam va hayotiy sikl xizmatlari'),
            ]),
            ('p', X('Our objective is not simply to provide communication equipment, but to establish a reliable and integrated communications capability that supports the customer\'s operational requirements.',
                    'Наша цель — не просто поставить средства связи, а создать надёжную интегрированную систему связи, отвечающую операционным требованиям заказчика.',
                    'Maqsadimiz shunchaki aloqa uskunalarini yetkazib berish emas, balki buyurtmachining operatsion talablariga javob beradigan ishonchli va integratsiyalashgan aloqa imkoniyatini yaratishdir.')),
        ],
    },
    {
        'id': 'command-control',
        'title': X('Command & Control (C2)', 'Командование и управление (C2)', 'Qo‘mondonlik va boshqaruv (C2)'),
        'subtitle': X('Information Where It Is Needed, When It Is Needed.', 'Информация там, где она нужна, и тогда, когда она нужна.', 'Axborot kerakli joyda va kerakli vaqtda.'),
        'items': [
            ('p', X('S3 provides Command and Control (C2) solutions designed to improve situational awareness, information sharing, coordination, and decision-making.',
                    'S3 предоставляет решения командования и управления (C2), которые повышают ситуационную осведомлённость, улучшают обмен информацией, координацию и принятие решений.',
                    'S3 vaziyatdan xabardorlik, axborot almashinuvi, muvofiqlashtirish va qaror qabul qilishni yaxshilashga mo‘ljallangan qo‘mondonlik va boshqaruv (C2) yechimlarini taqdim etadi.')),
            ('p', X('C2 solutions can bring together information from users, tactical networks, operational platforms, sensors, and other systems to provide relevant personnel with a shared understanding of the operational environment.',
                    'Решения C2 объединяют информацию от пользователей, тактических сетей, операционных платформ, датчиков и других систем, формируя у соответствующего персонала единое понимание операционной обстановки.',
                    'C2 yechimlari foydalanuvchilar, taktik tarmoqlar, operatsion platformalar, sensorlar va boshqa tizimlardan kelgan axborotni birlashtirib, tegishli xodimlarda operatsion muhit haqida umumiy tasavvur hosil qiladi.')),
            ('p', X('Depending on customer requirements, capabilities can include:', 'В зависимости от требований заказчика возможности могут включать:', 'Buyurtmachi talablariga qarab imkoniyatlar quyidagilarni o‘z ichiga olishi mumkin:')),
            ('list', [
                X('Common operational picture', 'Единая картина оперативной обстановки', 'Yagona operativ vaziyat manzarasi'),
                X('Tactical mapping and geospatial information', 'Тактические карты и геопространственная информация', 'Taktik xaritalar va geofazoviy axborot'),
                X('Position and status information', 'Информация о местоположении и состоянии', 'Joylashuv va holat to‘g‘risidagi axborot'),
                X('Operational reporting', 'Оперативная отчётность', 'Operativ hisobotlar'),
                X('Messaging and information exchange', 'Обмен сообщениями и информацией', 'Xabar va axborot almashinuvi'),
                X('Mission and operational planning', 'Планирование задач и операций', 'Vazifalar va operatsiyalarni rejalashtirish'),
                X('Command and control information exchange', 'Обмен информацией командования и управления', 'Qo‘mondonlik va boshqaruv axboroti almashinuvi'),
                X('Integration with tactical radio networks', 'Интеграция с тактическими радиосетями', 'Taktik radiotarmoqlar bilan integratsiya'),
                X('Integration with other operational systems and data sources', 'Интеграция с другими операционными системами и источниками данных', 'Boshqa operatsion tizimlar va ma’lumot manbalari bilan integratsiya'),
            ]),
            ('p', X('S3 supports the complete implementation process, including solution design, integration, configuration, deployment, training, and ongoing technical support.',
                    'S3 сопровождает весь процесс внедрения: проектирование решения, интеграцию, настройку, развёртывание, обучение и постоянную техническую поддержку.',
                    'S3 joriy etishning butun jarayonini — yechimni loyihalash, integratsiya, sozlash, joriy etish, o‘qitish va doimiy texnik yordamni qo‘llab-quvvatlaydi.')),
        ],
    },
    {
        'id': 'fire-support-targeting',
        'title': X('Fire Support & Targeting', 'Огневая поддержка и целеуказание', 'O‘t bilan qo‘llab-quvvatlash va nishon ko‘rsatish'),
        'subtitle': X('Connecting Information, Coordination, and Action', 'Связываем информацию, координацию и действия', 'Axborot, muvofiqlashtirish va harakatni bog‘laymiz'),
        'items': [
            ('p', X('Effective fire support depends on the timely and accurate exchange of information between the personnel and systems involved in observation, targeting, coordination, command and control, and execution.',
                    'Эффективная огневая поддержка зависит от своевременного и точного обмена информацией между персоналом и системами, задействованными в наблюдении, целеуказании, координации, командовании и управлении, а также исполнении.',
                    'Samarali o‘t bilan qo‘llab-quvvatlash kuzatuv, nishon ko‘rsatish, muvofiqlashtirish, qo‘mondonlik va boshqaruv hamda ijroda ishtirok etuvchi xodimlar va tizimlar o‘rtasida axborotning o‘z vaqtida va aniq almashinuviga bog‘liq.')),
            ('p', X('S3 provides and integrates Fire Support and Targeting Systems designed to support this information flow within the customer\'s operational environment.',
                    'S3 поставляет и интегрирует системы огневой поддержки и целеуказания, обеспечивающие этот информационный поток в операционной среде заказчика.',
                    'S3 buyurtmachining operatsion muhitida ushbu axborot oqimini ta’minlashga mo‘ljallangan o‘t bilan qo‘llab-quvvatlash va nishon ko‘rsatish tizimlarini yetkazib beradi va integratsiya qiladi.')),
            ('p', X('Solutions may combine:', 'Решения могут объединять:', 'Yechimlar quyidagilarni birlashtirishi mumkin:')),
            ('list', [
                X('Target acquisition and reporting capabilities', 'Средства обнаружения целей и передачи донесений', 'Nishonlarni aniqlash va xabar berish vositalari'),
                X('Positioning and geospatial information', 'Позиционирование и геопространственная информация', 'Joylashuvni aniqlash va geofazoviy axborot'),
                X('Tactical communications', 'Тактическая связь', 'Taktik aloqa'),
                X('Digital information exchange', 'Цифровой обмен информацией', 'Raqamli axborot almashinuvi'),
                X('Command and control applications', 'Приложения командования и управления', 'Qo‘mondonlik va boshqaruv ilovalari'),
                X('Relevant sensors and observation systems', 'Соответствующие датчики и системы наблюдения', 'Tegishli sensorlar va kuzatuv tizimlari'),
                X('Integration with supporting operational platforms and systems', 'Интеграция со вспомогательными операционными платформами и системами', 'Yordamchi operatsion platformalar va tizimlar bilan integratsiya'),
            ]),
            ('p', X('Our integration approach focuses on establishing reliable information exchange between the appropriate elements while supporting interoperability with the customer\'s wider communications and command-and-control environment.',
                    'Наш подход к интеграции направлен на создание надёжного обмена информацией между нужными элементами при сохранении совместимости с более широкой средой связи, командования и управления заказчика.',
                    'Integratsiyaga yondashuvimiz tegishli elementlar o‘rtasida ishonchli axborot almashinuvini yo‘lga qo‘yishga, shu bilan birga buyurtmachining kengroq aloqa, qo‘mondonlik va boshqaruv muhiti bilan o‘zaro moslikni ta’minlashga qaratilgan.')),
        ],
    },
    {
        'id': 'tactical-data-networks',
        'title': X('Tactical Data Networks', 'Тактические сети передачи данных', 'Taktik ma’lumot uzatish tarmoqlari'),
        'subtitle': X('Connecting the Operational Environment', 'Связываем операционную среду', 'Operatsion muhitni bog‘laymiz'),
        'items': [
            ('p', X('Modern tactical systems depend on resilient networks capable of transporting information securely between users, platforms, command posts, sensors, and applications.',
                    'Современные тактические системы зависят от устойчивых сетей, способных безопасно передавать информацию между пользователями, платформами, командными пунктами, датчиками и приложениями.',
                    'Zamonaviy taktik tizimlar foydalanuvchilar, platformalar, qo‘mondonlik punktlari, sensorlar va ilovalar o‘rtasida axborotni xavfsiz uzata oladigan barqaror tarmoqlarga tayanadi.')),
            ('p', X('S3 designs and integrates tactical data networking solutions supporting voice, data, C2, situational awareness, and other mission-critical services.',
                    'S3 проектирует и интегрирует решения тактических сетей передачи данных для голосовой связи, данных, C2, ситуационной осведомлённости и других критически важных сервисов.',
                    'S3 ovozli aloqa, ma’lumotlar, C2, vaziyatdan xabardorlik va boshqa o‘ta muhim xizmatlarni ta’minlaydigan taktik ma’lumot uzatish tarmoqlari yechimlarini loyihalaydi va integratsiya qiladi.')),
            ('p', X('Solutions can include radio-based tactical networks, IP networking, mobile and deployable network infrastructure, network management, and integration between different communications technologies.',
                    'Решения могут включать тактические радиосети, IP-сети, мобильную и развёртываемую сетевую инфраструктуру, управление сетями и интеграцию различных технологий связи.',
                    'Yechimlar radio asosidagi taktik tarmoqlar, IP-tarmoqlar, mobil va joylashtiriladigan tarmoq infratuzilmasi, tarmoqni boshqarish hamda turli aloqa texnologiyalarini o‘zaro integratsiya qilishni o‘z ichiga olishi mumkin.')),
            ('p', X('The objective is to create a communications environment in which information can move securely and reliably to the users and systems that need it.',
                    'Цель — создать среду связи, в которой информация безопасно и надёжно поступает к тем пользователям и системам, которым она нужна.',
                    'Maqsad — axborot unga muhtoj foydalanuvchilar va tizimlarga xavfsiz va ishonchli yetib boradigan aloqa muhitini yaratish.')),
        ],
    },
    {
        'id': 'satcom',
        'title': X('SATCOM', 'Спутниковая связь (SATCOM)', 'Sun’iy yo‘ldosh aloqasi (SATCOM)'),
        'subtitle': X('Communications Beyond Terrestrial Networks', 'Связь за пределами наземных сетей', 'Yer usti tarmoqlaridan tashqaridagi aloqa'),
        'items': [
            ('p', X('Satellite communications can provide connectivity where terrestrial infrastructure is unavailable, insufficient, or operationally unsuitable.',
                    'Спутниковая связь обеспечивает подключение там, где наземная инфраструктура отсутствует, недостаточна или не подходит для выполнения задач.',
                    'Sun’iy yo‘ldosh aloqasi yer usti infratuzilmasi mavjud bo‘lmagan, yetarli bo‘lmagan yoki operatsion jihatdan yaroqsiz joylarda aloqani ta’minlay oladi.')),
            ('p', X('S3 can provide SATCOM solutions as standalone capabilities or as part of wider tactical and operational communications architectures.',
                    'S3 может предоставлять решения SATCOM как самостоятельные средства или как часть более широкой архитектуры тактической и оперативной связи.',
                    'S3 SATCOM yechimlarini mustaqil imkoniyat sifatida yoki kengroq taktik va operatsion aloqa arxitekturasining bir qismi sifatida taqdim eta oladi.')),
            ('p', X('Depending on operational requirements, satellite connectivity can be integrated with command posts, tactical networks, C2 applications, deployable infrastructure, and other communication systems to extend connectivity across dispersed locations.',
                    'В зависимости от операционных требований спутниковую связь можно интегрировать с командными пунктами, тактическими сетями, приложениями C2, развёртываемой инфраструктурой и другими системами связи, чтобы обеспечить связь между удалёнными друг от друга пунктами.',
                    'Operatsion talablarga qarab, sun’iy yo‘ldosh aloqasi bir-biridan uzoqda joylashgan nuqtalar o‘rtasida aloqani kengaytirish uchun qo‘mondonlik punktlari, taktik tarmoqlar, C2 ilovalari, joylashtiriladigan infratuzilma va boshqa aloqa tizimlari bilan integratsiya qilinishi mumkin.')),
        ],
    },
    {
        'id': 'isr',
        'title': X('ISR Solutions', 'Решения ISR', 'ISR yechimlari'),
        'subtitle': X('Information Supporting Situational Awareness', 'Информация для ситуационной осведомлённости', 'Vaziyatdan xabardorlikni ta’minlovchi axborot'),
        'items': [
            ('p', X('Intelligence, Surveillance and Reconnaissance (ISR) capabilities help organizations collect, distribute, and use information required to understand the operational environment.',
                    'Средства разведки, наблюдения и рекогносцировки (ISR) помогают организациям собирать, распространять и использовать информацию, необходимую для понимания операционной обстановки.',
                    'Razvedka, kuzatuv va rekognossirovka (ISR) imkoniyatlari tashkilotlarga operatsion muhitni tushunish uchun zarur bo‘lgan axborotni to‘plash, tarqatish va undan foydalanishda yordam beradi.')),
            ('p', X('S3 can integrate ISR technologies and information sources with communications, networking, C2, and other operational systems.',
                    'S3 может интегрировать технологии и источники информации ISR с системами связи, сетями, C2 и другими операционными системами.',
                    'S3 ISR texnologiyalari va axborot manbalarini aloqa, tarmoqlar, C2 va boshqa operatsion tizimlar bilan integratsiya qila oladi.')),
            ('p', X('Our focus is on ensuring that relevant information can be securely transported, presented, and shared with authorized users as part of the wider operational environment.',
                    'Мы уделяем особое внимание тому, чтобы нужная информация безопасно передавалась, отображалась и была доступна авторизованным пользователям в рамках общей операционной среды.',
                    'Asosiy e’tiborimiz — kerakli axborotning umumiy operatsion muhit doirasida xavfsiz uzatilishi, taqdim etilishi va vakolatli foydalanuvchilar bilan ulashilishini ta’minlash.')),
        ],
    },
    {
        'id': 'uav-integration',
        'title': X('UAV Integration', 'Интеграция БПЛА', 'Uchuvchisiz uchish apparatlarini (UAV) integratsiya qilish'),
        'subtitle': X('Connecting Unmanned Systems to the Operational Network', 'Подключаем беспилотные системы к операционной сети', 'Uchuvchisiz tizimlarni operatsion tarmoqqa ulaymiz'),
        'items': [
            ('p', X('Unmanned aerial systems can provide valuable information to commanders, operational personnel, and other authorized users.',
                    'Беспилотные авиационные системы могут предоставлять ценную информацию командирам, оперативному персоналу и другим авторизованным пользователям.',
                    'Uchuvchisiz uchish tizimlari qo‘mondonlar, operativ xodimlar va boshqa vakolatli foydalanuvchilarga qimmatli axborot yetkaza oladi.')),
            ('p', X('S3 supports the integration of UAV capabilities with communications, networks, C2, and ISR environments, helping make information generated by unmanned platforms available to the systems and personnel that require it.',
                    'S3 содействует интеграции возможностей БПЛА со средами связи, сетей, C2 и ISR, помогая сделать информацию от беспилотных платформ доступной для систем и персонала, которым она необходима.',
                    'S3 UAV imkoniyatlarini aloqa, tarmoqlar, C2 va ISR muhitlari bilan integratsiya qilishda ko‘maklashadi va uchuvchisiz platformalar yaratgan axborotni unga muhtoj tizimlar va xodimlar uchun ochiq qiladi.')),
            ('p', X('Depending on customer requirements and selected technologies, integration may include data connectivity, information distribution, situational-awareness applications, and command-post environments.',
                    'В зависимости от требований заказчика и выбранных технологий интеграция может включать каналы передачи данных, распространение информации, приложения ситуационной осведомлённости и среду командных пунктов.',
                    'Buyurtmachi talablari va tanlangan texnologiyalarga qarab, integratsiya ma’lumot uzatish aloqasi, axborotni tarqatish, vaziyatdan xabardorlik ilovalari va qo‘mondonlik punktlari muhitini o‘z ichiga olishi mumkin.')),
        ],
    },
    {
        'id': 'electronic-warfare',
        'title': X('Electronic Warfare', 'Радиоэлектронная борьба', 'Radioelektron kurash'),
        'subtitle': X('Integrated Capabilities for the Electromagnetic Environment', 'Интегрированные возможности для электромагнитной среды', 'Elektromagnit muhit uchun integratsiyalashgan imkoniyatlar'),
        'items': [
            ('p', X('S3 can provide and integrate Electronic Warfare (EW) technologies in cooperation with specialized technology partners.',
                    'S3 может поставлять и интегрировать технологии радиоэлектронной борьбы (РЭБ) в сотрудничестве со специализированными технологическими партнёрами.',
                    'S3 ixtisoslashgan texnologik hamkorlar bilan hamkorlikda radioelektron kurash (EW) texnologiyalarini yetkazib bera oladi va integratsiya qila oladi.')),
            ('p', X('Solutions may support capabilities related to the detection, analysis, monitoring, and management of activity within the electromagnetic environment, depending on customer requirements and the technologies selected.',
                    'В зависимости от требований заказчика и выбранных технологий решения могут поддерживать обнаружение, анализ, мониторинг активности в электромагнитной среде и управление ею.',
                    'Buyurtmachi talablari va tanlangan texnologiyalarga qarab, yechimlar elektromagnit muhitdagi faollikni aniqlash, tahlil qilish, kuzatish va boshqarish bilan bog‘liq imkoniyatlarni qo‘llab-quvvatlashi mumkin.')),
            ('p', X('Where appropriate, EW capabilities can be integrated with communications, command and control, ISR, and other operational systems to support a broader understanding of the operational environment.',
                    'При необходимости возможности РЭБ можно интегрировать с системами связи, командования и управления, ISR и другими операционными системами для более полного понимания операционной обстановки.',
                    'Zarur hollarda EW imkoniyatlari operatsion muhitni kengroq tushunish uchun aloqa, qo‘mondonlik va boshqaruv, ISR va boshqa operatsion tizimlar bilan integratsiya qilinishi mumkin.')),
        ],
    },
    {
        'id': 'cybersecurity',
        'title': X('Cybersecurity', 'Кибербезопасность', 'Kiberxavfsizlik'),
        'subtitle': X('Protecting Mission-Critical Information and Systems', 'Защита критически важной информации и систем', 'O‘ta muhim axborot va tizimlarni himoya qilish'),
        'items': [
            ('p', X('As operational systems become increasingly connected, cybersecurity becomes an essential component of mission-critical infrastructure.',
                    'По мере того как операционные системы становятся всё более связанными, кибербезопасность становится неотъемлемой частью критически важной инфраструктуры.',
                    'Operatsion tizimlar tobora ko‘proq o‘zaro bog‘lanib borar ekan, kiberxavfsizlik o‘ta muhim infratuzilmaning ajralmas qismiga aylanmoqda.')),
            ('p', X('S3 considers security throughout the solution lifecycle and can provide cybersecurity technologies and services in cooperation with specialized partners.',
                    'S3 учитывает вопросы безопасности на протяжении всего жизненного цикла решения и может предоставлять технологии и услуги кибербезопасности совместно со специализированными партнёрами.',
                    'S3 xavfsizlikni yechimning butun hayotiy sikli davomida hisobga oladi va ixtisoslashgan hamkorlar bilan birgalikda kiberxavfsizlik texnologiyalari va xizmatlarini taqdim eta oladi.')),
            ('p', X('Depending on requirements, cybersecurity capabilities can support the protection of networks, systems, applications, communications, and operational information, while complementing the customer\'s wider security architecture.',
                    'В зависимости от требований средства кибербезопасности помогают защищать сети, системы, приложения, связь и оперативную информацию, дополняя общую архитектуру безопасности заказчика.',
                    'Talablarga qarab, kiberxavfsizlik vositalari buyurtmachining umumiy xavfsizlik arxitekturasini to‘ldirgan holda tarmoqlar, tizimlar, ilovalar, aloqa va operativ axborotni himoya qilishga yordam beradi.')),
        ],
    },
    {
        'id': 'command-post-infrastructure',
        'title': X('Command-Post Infrastructure', 'Инфраструктура командных пунктов', 'Qo‘mondonlik punktlari infratuzilmasi'),
        'subtitle': X('An Integrated Environment for Command and Control', 'Интегрированная среда для командования и управления', 'Qo‘mondonlik va boshqaruv uchun integratsiyalashgan muhit'),
        'items': [
            ('p', X('Command posts require more than individual communications and IT systems. They depend on an integrated technical environment capable of supporting communications, networking, information systems, situational awareness, and command-and-control functions.',
                    'Командным пунктам нужны не просто отдельные системы связи и ИТ. Им необходима интегрированная техническая среда, поддерживающая связь, сети, информационные системы, ситуационную осведомлённость и функции командования и управления.',
                    'Qo‘mondonlik punktlariga alohida aloqa va AT tizimlarining o‘zi yetarli emas. Ular aloqa, tarmoqlar, axborot tizimlari, vaziyatdan xabardorlik hamda qo‘mondonlik va boshqaruv funksiyalarini qo‘llab-quvvatlay oladigan integratsiyalashgan texnik muhitga tayanadi.')),
            ('p', X('S3 can design and integrate command-post infrastructure combining relevant technologies into a coordinated operational environment.',
                    'S3 может проектировать и интегрировать инфраструктуру командных пунктов, объединяя необходимые технологии в согласованную операционную среду.',
                    'S3 tegishli texnologiyalarni muvofiqlashtirilgan operatsion muhitga birlashtirib, qo‘mondonlik punktlari infratuzilmasini loyihalashi va integratsiya qilishi mumkin.')),
            ('p', X('Solutions can incorporate:', 'Решения могут включать:', 'Yechimlar quyidagilarni o‘z ichiga olishi mumkin:')),
            ('list', [
                X('Secure communications', 'Защищённую связь', 'Himoyalangan aloqa'),
                X('Tactical and IP networking', 'Тактические и IP-сети', 'Taktik va IP-tarmoqlar'),
                X('C2 systems', 'Системы C2', 'C2 tizimlari'),
                X('Operator workstations', 'Автоматизированные рабочие места операторов', 'Operatorlarning ish o‘rinlari'),
                X('Displays and visualization', 'Дисплеи и средства визуализации', 'Displeylar va vizualizatsiya vositalari'),
                X('Servers and supporting IT infrastructure', 'Серверы и вспомогательную ИТ-инфраструктуру', 'Serverlar va yordamchi AT infratuzilmasi'),
                X('Power and connectivity infrastructure', 'Инфраструктуру электропитания и подключения', 'Elektr ta’minoti va ulanish infratuzilmasi'),
                X('Integration with external operational systems', 'Интеграцию с внешними операционными системами', 'Tashqi operatsion tizimlar bilan integratsiya'),
            ]),
            ('p', X('Solutions can be developed for fixed, mobile, or deployable environments according to customer requirements.',
                    'Решения могут создаваться для стационарных, мобильных или развёртываемых условий в соответствии с требованиями заказчика.',
                    'Yechimlar buyurtmachi talablariga muvofiq statsionar, mobil yoki joylashtiriladigan sharoitlar uchun ishlab chiqilishi mumkin.')),
        ],
    },
    {
        'id': 'deployable-communications',
        'title': X('Deployable Communication Systems', 'Развёртываемые системы связи', 'Joylashtiriladigan aloqa tizimlari'),
        'subtitle': X('Mission-Critical Connectivity Where It Is Needed', 'Критически важная связь там, где она нужна', 'O‘ta muhim aloqa — kerakli joyda'),
        'items': [
            ('p', X('Operational requirements frequently demand communications and information capabilities outside permanent facilities.',
                    'Операционные требования часто предполагают наличие связи и информационных возможностей за пределами стационарных объектов.',
                    'Operatsion talablar ko‘pincha doimiy obyektlardan tashqarida aloqa va axborot imkoniyatlarini talab qiladi.')),
            ('p', X('S3 can provide mobile and deployable communication solutions designed to establish communications, networking, and command-and-control capabilities in temporary or rapidly established operational locations.',
                    'S3 может предоставлять мобильные и развёртываемые решения связи, позволяющие организовать связь, сети и возможности командования и управления во временных или быстро развёртываемых пунктах.',
                    'S3 vaqtinchalik yoki tezkor tashkil etiladigan operatsion joylarda aloqa, tarmoq hamda qo‘mondonlik va boshqaruv imkoniyatlarini yaratishga mo‘ljallangan mobil va joylashtiriladigan aloqa yechimlarini taqdim eta oladi.')),
            ('p', X('Solutions may combine tactical radios, networking, SATCOM, C2 applications, IT infrastructure, power systems, and other supporting technologies into an integrated deployable capability.',
                    'Решения могут объединять тактические радиостанции, сети, SATCOM, приложения C2, ИТ-инфраструктуру, системы электропитания и другие вспомогательные технологии в единый развёртываемый комплекс.',
                    'Yechimlar taktik radiostansiyalar, tarmoqlar, SATCOM, C2 ilovalari, AT infratuzilmasi, elektr ta’minoti tizimlari va boshqa yordamchi texnologiyalarni yagona joylashtiriladigan imkoniyatga birlashtirishi mumkin.')),
        ],
    },
]

PAGE = {
    'slug': 'solutions.html',
    'title': X('Solutions', 'Решения', 'Yechimlar'),
    'image': 'radio-detail.webp',
    'hero': {
        'title': X('Integrated Technologies for Mission-Critical Operations', 'Интегрированные технологии для критически важных операций', 'O‘ta muhim operatsiyalar uchun integratsiyalashgan texnologiyalar'),
        'lead': X('S3 provides integrated technology solutions designed to support secure communications, command and control, situational awareness, information exchange, coordination, and operational effectiveness.',
                  'S3 предоставляет интегрированные технологические решения для защищённой связи, командования и управления, ситуационной осведомлённости, обмена информацией, координации и повышения операционной эффективности.',
                  'S3 himoyalangan aloqa, qo‘mondonlik va boshqaruv, vaziyatdan xabardorlik, axborot almashinuvi, muvofiqlashtirish va operatsion samaradorlikni ta’minlashga mo‘ljallangan integratsiyalashgan texnologik yechimlarni taqdim etadi.'),
    },
    'blocks': [
        ('continuation', {'items': [
            ('p', X('We do not approach technologies as isolated products. Working with our customers and technology partners, we combine appropriate systems, networks, applications, platforms, and infrastructure into solutions designed around specific operational requirements.',
                    'Мы не рассматриваем технологии как отдельные продукты. Вместе с заказчиками и технологическими партнёрами мы объединяем подходящие системы, сети, приложения, платформы и инфраструктуру в решения, построенные вокруг конкретных операционных требований.',
                    'Biz texnologiyalarga alohida mahsulotlar sifatida yondashmaymiz. Buyurtmachilarimiz va texnologik hamkorlarimiz bilan birgalikda mos tizimlar, tarmoqlar, ilovalar, platformalar va infratuzilmani aniq operatsion talablar asosida yaratilgan yechimlarga birlashtiramiz.')),
            ('p', X('Our portfolio includes both established S3 core capabilities and complementary technologies that can be integrated to create a complete operational solution.',
                    'Наш портфель включает как основные компетенции S3, так и дополняющие их технологии, которые можно интегрировать в законченное операционное решение.',
                    'Portfelimiz S3 ning asosiy imkoniyatlarini ham, yaxlit operatsion yechim yaratish uchun integratsiya qilinishi mumkin bo‘lgan qo‘shimcha texnologiyalarni ham o‘z ichiga oladi.')),
        ]}),
        ('anchors', {'links': [(area['id'], area['title']) for area in AREAS]}),
        ('details', {'rows': AREAS}),
        ('prose', {'title': X('One Integrated Approach', 'Единый интегрированный подход', 'Yagona integratsiyalashgan yondashuv'), 'items': [
            ('p', X('Individual technologies provide the greatest operational value when they work together.',
                    'Отдельные технологии приносят наибольшую операционную пользу, когда работают вместе.',
                    'Alohida texnologiyalar birgalikda ishlaganda eng katta operatsion foyda keltiradi.')),
            ('p', X('A secure radio network can transport C2 information. A tactical network can connect a command post with mobile users and platforms. ISR information can contribute to situational awareness. SATCOM can extend connectivity beyond the reach of terrestrial networks.',
                    'Защищённая радиосеть может передавать информацию C2. Тактическая сеть может связать командный пункт с мобильными пользователями и платформами. Информация ISR повышает ситуационную осведомлённость. SATCOM расширяет связь за пределы досягаемости наземных сетей.',
                    'Himoyalangan radiotarmoq C2 axborotini uzata oladi. Taktik tarmoq qo‘mondonlik punktini mobil foydalanuvchilar va platformalar bilan bog‘lay oladi. ISR axboroti vaziyatdan xabardorlikka hissa qo‘shadi. SATCOM aloqani yer usti tarmoqlari yeta olmaydigan joylargacha kengaytiradi.')),
            ('emphasis', X('S3 brings these technologies together.', 'S3 объединяет эти технологии.', 'S3 bu texnologiyalarni birlashtiradi.')),
            ('p', X('Our role as a systems integrator is to determine how individual capabilities should connect, exchange information, and operate as part of a complete solution while considering the systems and infrastructure already available to the customer.',
                    'Наша роль как системного интегратора — определить, как отдельные возможности должны соединяться, обмениваться информацией и работать в составе законченного решения, с учётом систем и инфраструктуры, уже имеющихся у заказчика.',
                    'Tizim integratori sifatidagi vazifamiz — buyurtmachida allaqachon mavjud tizimlar va infratuzilmani hisobga olgan holda, alohida imkoniyatlar qanday ulanishi, axborot almashishi va yaxlit yechim tarkibida ishlashi kerakligini belgilash.')),
            ('p', X('This approach enables customers to introduce new technologies progressively while supporting interoperability and making effective use of existing investments.',
                    'Такой подход позволяет заказчикам внедрять новые технологии поэтапно, сохраняя совместимость и эффективно используя уже сделанные инвестиции.',
                    'Bu yondashuv buyurtmachilarga o‘zaro moslikni saqlagan va mavjud investitsiyalardan samarali foydalangan holda yangi texnologiyalarni bosqichma-bosqich joriy etish imkonini beradi.')),
        ]}),
        ('prose', {'title': X('From Solution Design to Lifecycle Support', 'От проектирования решения до поддержки жизненного цикла', 'Yechimni loyihalashdan hayotiy sikl davomida qo‘llab-quvvatlashgacha'), 'soft': True, 'items': [
            ('p', X('Every S3 solution can be supported throughout its lifecycle:',
                    'Каждое решение S3 может сопровождаться на протяжении всего жизненного цикла:',
                    'Har bir S3 yechimi butun hayotiy sikli davomida qo‘llab-quvvatlanishi mumkin:')),
            ('flow', [
                X('Requirements Analysis', 'Анализ требований', 'Talablarni tahlil qilish'),
                X('Solution Design', 'Проектирование решения', 'Yechimni loyihalash'),
                X('Systems Integration', 'Системная интеграция', 'Tizim integratsiyasi'),
                X('Deployment & Configuration', 'Развёртывание и настройка', 'Joriy etish va sozlash'),
                X('Testing', 'Испытания', 'Sinovdan o‘tkazish'),
                X('Training & Knowledge Transfer', 'Обучение и передача знаний', 'O‘qitish va bilim uzatish'),
                X('Technical Support', 'Техническая поддержка', 'Texnik yordam'),
            ]),
            ('p', X('Working alongside our customers and technology partners, we aim to ensure that the technologies we provide become effective, sustainable operational capabilities rather than standalone products.',
                    'Работая вместе с заказчиками и технологическими партнёрами, мы стремимся к тому, чтобы предоставляемые нами технологии становились эффективными и устойчивыми операционными возможностями, а не отдельными продуктами.',
                    'Buyurtmachilarimiz va texnologik hamkorlarimiz bilan birga ishlab, biz taqdim etayotgan texnologiyalar alohida mahsulot emas, balki samarali va barqaror operatsion imkoniyatga aylanishiga intilamiz.')),
        ]}),
        ('closing', {'statement': BRAND_STATEMENT, 'buttons': [
            (X('Discuss Your Requirements', 'Обсудить ваши требования', 'Talablaringizni muhokama qilish'), 'contact.html?interest=requirement', 'primary-link'),
            (SYSTEMS_INTEGRATION, 'systems-integration.html', 'text-link'),
        ]}),
    ],
}
