from . import X, BRAND_STATEMENT, CONTACT_S3, TRAINING

PAGE = {
    'slug': 'support.html',
    'title': X('Support & FSR Services', 'Поддержка и FSR', 'Yordam va FSR xizmatlari'),
    'image': 'radio-detail.webp',
    'hero': {
        'title': X('Support Where It Matters', 'Поддержка там, где она важна', 'Muhim joyda qo‘llab-quvvatlash'),
        'lead': X('Mission-critical systems require more than successful delivery and installation.',
                  'Критически важным системам нужно больше, чем успешная поставка и установка.',
                  'O‘ta muhim tizimlar uchun muvaffaqiyatli yetkazib berish va o‘rnatishning o‘zi yetarli emas.'),
    },
    'blocks': [
        ('intro', {'items': [
            ('p', X('Once a solution becomes operational, customers need access to reliable technical expertise, effective troubleshooting, continued knowledge transfer, and support that understands both the technology and the environment in which it is used.',
                    'Когда решение введено в эксплуатацию, заказчикам нужен доступ к надёжной технической экспертизе, эффективному устранению неисправностей, постоянной передаче знаний и поддержке, которая понимает как технологию, так и среду, в которой она используется.',
                    'Yechim ishga tushirilgach, buyurtmachilarga ishonchli texnik ekspertiza, nosozliklarni samarali bartaraf etish, bilimlarni doimiy uzatish hamda texnologiyani ham, u qo‘llaniladigan muhitni ham tushunadigan qo‘llab-quvvatlash zarur bo‘ladi.')),
            ('p', X('For this reason, S3 provides lifecycle support and Field Service Representative (FSR) services for the solutions we deliver.',
                           'Поэтому S3 оказывает поддержку жизненного цикла и предоставляет услуги выездных технических специалистов (FSR) для поставляемых решений.',
                           'Shu sababli S3 o‘zi yetkazib beradigan yechimlar uchun hayotiy sikl davomida qo‘llab-quvvatlash va joylardagi texnik vakillar (FSR) xizmatlarini taqdim etadi.')),
        ]}),
        ('prose', {'title': X('Local Presence. International Expertise.', 'Местное присутствие. Международная экспертиза.', 'Mahalliy vakillik. Xalqaro ekspertiza.'), 'soft': True, 'items': [
            ('p', X('Technical support is most effective when expertise is available close to the customer.',
                    'Техническая поддержка наиболее эффективна, когда экспертиза доступна рядом с заказчиком.',
                    'Texnik yordam ekspertiza buyurtmachiga yaqin bo‘lganda eng samarali bo‘ladi.')),
            ('p', X('S3\'s support model combines local presence with access to international technical expertise.',
                    'Модель поддержки S3 сочетает местное присутствие с доступом к международной технической экспертизе.',
                    'S3 ning qo‘llab-quvvatlash modeli mahalliy vakillikni xalqaro texnik ekspertizadan foydalanish imkoniyati bilan uyg‘unlashtiradi.')),
            ('p', X('Where required, experienced Field Service Representatives can work locally alongside customer personnel, providing direct assistance with deployed systems while maintaining access to S3, our integration partners, and technology manufacturers.',
                    'При необходимости опытные выездные технические специалисты (FSR) работают на месте вместе с персоналом заказчика, напрямую помогая с развёрнутыми системами и сохраняя связь с S3, нашими партнёрами по интеграции и производителями технологий.',
                    'Zarur hollarda tajribali joylardagi texnik vakillar (FSR) buyurtmachi xodimlari bilan birga joyida ishlab, joriy etilgan tizimlar bo‘yicha bevosita yordam ko‘rsatadi va S3, integratsiya bo‘yicha hamkorlarimiz hamda texnologiya ishlab chiqaruvchilari bilan aloqani saqlaydi.')),
            ('p', X('This creates a support structure that connects:', 'Так создаётся структура поддержки, которая связывает:', 'Shu tariqa quyidagilarni bog‘laydigan qo‘llab-quvvatlash tuzilmasi yaratiladi:')),
            ('flow', [
                X('Customer Personnel', 'Персонал заказчика', 'Buyurtmachi xodimlari'),
                X('Local FSR', 'Местный FSR', 'Mahalliy FSR'),
                X('S3', 'S3', 'S3'),
                X('Integration Partners', 'Партнёры по интеграции', 'Integratsiya bo‘yicha hamkorlar'),
                X('Technology Manufacturer', 'Производитель технологий', 'Texnologiya ishlab chiqaruvchisi'),
            ]),
            ('p', X('Routine issues can be addressed close to the customer, while more complex technical matters can be escalated to the appropriate level of specialist or manufacturer support.',
                    'Типовые вопросы решаются рядом с заказчиком, а более сложные технические задачи передаются на соответствующий уровень поддержки специалистов или производителя.',
                    'Odatiy masalalar buyurtmachiga yaqin joyda hal qilinadi, murakkabroq texnik masalalar esa mutaxassislar yoki ishlab chiqaruvchi yordamining tegishli darajasiga yo‘naltiriladi.')),
            ('p', X('The customer therefore benefits from a local point of technical assistance backed by a wider international support network.',
                    'Таким образом, заказчик получает местную точку технической помощи, за которой стоит более широкая международная сеть поддержки.',
                    'Shunday qilib, buyurtmachi kengroq xalqaro qo‘llab-quvvatlash tarmog‘iga tayangan mahalliy texnik yordam nuqtasiga ega bo‘ladi.')),
            ('p', X('Our objective is to help customers maintain system availability, resolve technical issues efficiently, develop internal expertise, and continue receiving value from their technology investments throughout the operational lifecycle.',
                    'Наша цель — помочь заказчикам поддерживать готовность систем, эффективно решать технические проблемы, развивать внутреннюю экспертизу и получать отдачу от инвестиций в технологии на протяжении всего жизненного цикла эксплуатации.',
                    'Maqsadimiz — buyurtmachilarga tizimlarning shayligini saqlash, texnik muammolarni samarali hal qilish, ichki ekspertizani rivojlantirish va butun foydalanish davri mobaynida texnologiyaga kiritgan investitsiyalaridan foyda olishda davom etishda yordam berish.')),
        ]}),
        ('prose', {'title': X('Field Service Representative (FSR)', 'Выездной технический специалист (FSR)', 'Joylardagi texnik vakil (FSR)'),
                   'subtitle': X('Expertise Close to the Customer', 'Экспертиза рядом с заказчиком', 'Buyurtmachiga yaqin ekspertiza'), 'items': [
            ('p', X('The FSR provides more than traditional technical support.',
                           'FSR — это больше, чем традиционная техническая поддержка.',
                           'FSR an’anaviy texnik yordamdan ko‘proq narsani taqdim etadi.')),
            ('p', X('The FSR works alongside customer personnel and develops an understanding of the deployed systems, technical environment, operational requirements, and recurring support needs.',
                    'FSR работает вместе с персоналом заказчика и глубоко изучает развёрнутые системы, техническую среду, операционные требования и повторяющиеся потребности в поддержке.',
                    'FSR buyurtmachi xodimlari bilan birga ishlaydi va joriy etilgan tizimlar, texnik muhit, operatsion talablar hamda takrorlanuvchi yordam ehtiyojlarini chuqur o‘rganadi.')),
            ('p', X('Where appropriate, FSR personnel combine technical expertise with relevant military and operational experience.',
                    'При необходимости специалисты FSR сочетают техническую экспертизу с соответствующим военным и операционным опытом.',
                    'Zarur hollarda FSR xodimlari texnik ekspertizani tegishli harbiy va operatsion tajriba bilan uyg‘unlashtiradi.')),
            ('p', X('This combination helps bridge the gap between technical functionality and operational use.',
                    'Такое сочетание помогает преодолеть разрыв между техническими функциями и их практическим применением.',
                    'Bu uyg‘unlik texnik funksionallik va operatsion foydalanish o‘rtasidagi tafovutni bartaraf etishga yordam beradi.')),
            ('p', X('Rather than considering a system only from an engineering perspective, an experienced FSR can better understand how the technology is used in practice and help customer personnel identify effective solutions to day-to-day technical challenges.',
                    'Опытный FSR рассматривает систему не только с инженерной точки зрения: он лучше понимает, как технология используется на практике, и помогает персоналу заказчика находить эффективные решения повседневных технических задач.',
                    'Tajribali FSR tizimga faqat muhandislik nuqtai nazaridan qaramaydi: u texnologiyadan amalda qanday foydalanilishini yaxshiroq tushunadi va buyurtmachi xodimlariga kundalik texnik muammolarning samarali yechimlarini topishda yordam beradi.')),
        ]}),
        ('cards', {
            'title': X('What an FSR Provides', 'Что предоставляет FSR', 'FSR nimalarni taqdim etadi'),
            'soft': True,
            'intro': [
                ('p', X('Depending on the solution and customer requirements, FSR services can include:',
                        'В зависимости от решения и требований заказчика услуги FSR могут включать:',
                        'Yechim va buyurtmachi talablariga qarab FSR xizmatlari quyidagilarni o‘z ichiga olishi mumkin:')),
            ],
            'cards': [
                (X('Technical Assistance', 'Техническая помощь', 'Texnik yordam'), [
                    X('Direct support to customer personnel in the operation, configuration, and technical management of deployed systems.',
                      'Непосредственная помощь персоналу заказчика в эксплуатации, настройке и техническом управлении развёрнутыми системами.',
                      'Joriy etilgan tizimlardan foydalanish, ularni sozlash va texnik boshqarishda buyurtmachi xodimlariga bevosita yordam.')]),
                (X('Troubleshooting', 'Устранение неисправностей', 'Nosozliklarni bartaraf etish'), [
                    X('Identification and analysis of technical issues, development of appropriate corrective actions, and coordination of additional specialist support when required.',
                      'Выявление и анализ технических проблем, разработка корректирующих мер и при необходимости привлечение дополнительных специалистов.',
                      'Texnik muammolarni aniqlash va tahlil qilish, tegishli tuzatish choralarini ishlab chiqish va zarur hollarda qo‘shimcha mutaxassislar yordamini muvofiqlashtirish.')]),
                (X('Configuration Support', 'Помощь в настройке', 'Sozlashda ko‘maklashish'), [
                    X('Assistance with system configuration, communications planning, network configuration, software settings, and other technical parameters within the agreed scope of support.',
                      'Помощь в настройке систем, планировании связи, конфигурировании сетей, настройке программного обеспечения и других технических параметров в согласованном объёме поддержки.',
                      'Kelishilgan qo‘llab-quvvatlash doirasida tizimni sozlash, aloqani rejalashtirish, tarmoqni sozlash, dasturiy ta’minot sozlamalari va boshqa texnik parametrlar bo‘yicha yordam.')]),
                (X('Knowledge Sharing', 'Обмен знаниями', 'Bilim almashish'), [
                    X('Continuous transfer of practical knowledge during day-to-day interaction with customer personnel.',
                      'Постоянная передача практических знаний в ходе повседневного взаимодействия с персоналом заказчика.',
                      'Buyurtmachi xodimlari bilan kundalik muloqot davomida amaliy bilimlarni doimiy uzatish.'),
                    X('This allows learning to continue beyond formal training sessions.',
                      'Это позволяет продолжать обучение и за пределами формальных занятий.',
                      'Bu o‘qishni rasmiy mashg‘ulotlardan tashqarida ham davom ettirish imkonini beradi.')]),
                (X('Training Reinforcement', 'Закрепление обучения', 'O‘qitish natijalarini mustahkamlash'), [
                    X('Support for personnel who have completed formal training by helping them apply acquired knowledge to real systems and practical technical tasks.',
                      'Поддержка персонала, прошедшего формальное обучение: помощь в применении полученных знаний на реальных системах и в практических технических задачах.',
                      'Rasmiy o‘qitishdan o‘tgan xodimlarga olgan bilimlarini haqiqiy tizimlarda va amaliy texnik vazifalarda qo‘llashda yordam berish.')]),
                (X('Support for Customer Instructors', 'Поддержка инструкторов заказчика', 'Buyurtmachi instruktorlarini qo‘llab-quvvatlash'), [
                    X('Where Train-the-Trainer programs have been delivered, FSR personnel can assist customer instructors as they develop their own experience and transfer knowledge within their organization.',
                      'Там, где проводились программы подготовки инструкторов, специалисты FSR помогают инструкторам заказчика набираться опыта и передавать знания внутри своей организации.',
                      'Trenerlarni tayyorlash dasturlari o‘tkazilgan joylarda FSR xodimlari buyurtmachi instruktorlariga o‘z tajribasini oshirish va bilimlarni o‘z tashkiloti ichida uzatishda yordam beradi.')]),
                (X('System Optimization', 'Оптимизация систем', 'Tizimlarni optimallashtirish'), [
                    X('Support in identifying configuration or implementation improvements that can help customers use deployed capabilities more effectively.',
                      'Помощь в поиске улучшений настройки или внедрения, позволяющих заказчикам эффективнее использовать развёрнутые возможности.',
                      'Buyurtmachilarga joriy etilgan imkoniyatlardan samaraliroq foydalanishga yordam beradigan sozlash yoki joriy etish bo‘yicha yaxshilanishlarni aniqlashda ko‘maklashish.')]),
                (X('Technical Coordination', 'Техническая координация', 'Texnik muvofiqlashtirish'), [
                    X('Coordination with S3, integration partners, and technology manufacturers when additional engineering expertise or higher-level technical support is required.',
                      'Взаимодействие с S3, партнёрами по интеграции и производителями технологий, когда требуется дополнительная инженерная экспертиза или техническая поддержка более высокого уровня.',
                      'Qo‘shimcha muhandislik ekspertizasi yoki yuqori darajadagi texnik yordam talab qilinganda S3, integratsiya bo‘yicha hamkorlar va texnologiya ishlab chiqaruvchilari bilan muvofiqlashtirish.')]),
                (X('Support for Updates and Modernization', 'Поддержка обновлений и модернизации', 'Yangilash va modernizatsiyani qo‘llab-quvvatlash'), [
                    X('Technical assistance when systems are expanded, updated, reconfigured, or integrated with additional capabilities.',
                      'Техническая помощь при расширении, обновлении, перенастройке систем или их интеграции с дополнительными возможностями.',
                      'Tizimlar kengaytirilganda, yangilanganda, qayta sozlanganda yoki qo‘shimcha imkoniyatlar bilan integratsiya qilinganda texnik yordam.')]),
            ],
        }),
        ('prose', {'title': X('More Than Troubleshooting', 'Больше, чем устранение неисправностей', 'Nosozliklarni bartaraf etishdan ko‘proq'), 'items': [
            ('p', X('A locally available specialist can continuously support the customer by answering technical questions, helping personnel apply their training, identifying potential issues, sharing practical experience, and assisting with system development.',
                    'Специалист, находящийся рядом, может постоянно поддерживать заказчика: отвечать на технические вопросы, помогать персоналу применять полученные навыки, выявлять потенциальные проблемы, делиться практическим опытом и помогать в развитии системы.',
                    'Joyida mavjud mutaxassis buyurtmachini doimiy qo‘llab-quvvatlay oladi: texnik savollarga javob beradi, xodimlarga o‘qishda olgan bilimlarini qo‘llashda yordam beradi, ehtimoliy muammolarni aniqlaydi, amaliy tajriba bilan o‘rtoqlashadi va tizimni rivojlantirishda ko‘maklashadi.')),
            ('p', X('The FSR becomes a technical link between the customer, S3, integration partners, and technology manufacturers, helping information and expertise move efficiently in both directions.',
                    'FSR становится техническим связующим звеном между заказчиком, S3, партнёрами по интеграции и производителями технологий, помогая информации и экспертизе эффективно передаваться в обоих направлениях.',
                    'FSR buyurtmachi, S3, integratsiya bo‘yicha hamkorlar va texnologiya ishlab chiqaruvchilari o‘rtasidagi texnik bo‘g‘inga aylanib, axborot va ekspertizaning har ikki yo‘nalishda samarali harakatlanishiga yordam beradi.')),
        ]}),
        ('prose', {'title': X('From Formal Training to Everyday Knowledge Transfer', 'От формального обучения — к ежедневной передаче знаний', 'Rasmiy o‘qitishdan — kundalik bilim uzatishgacha'), 'soft': True, 'items': [
            ('p', X('Formal training provides the foundation. Day-to-day experience develops expertise.',
                           'Формальное обучение закладывает основу. Повседневный опыт развивает экспертизу.',
                           'Rasmiy o‘qitish poydevor yaratadi. Kundalik tajriba ekspertizani rivojlantiradi.')),
            ('p', X('Following training, personnel inevitably encounter new questions and situations as they begin using systems independently.',
                    'После обучения, начиная самостоятельно работать с системами, персонал неизбежно сталкивается с новыми вопросами и ситуациями.',
                    'O‘qitishdan so‘ng tizimlardan mustaqil foydalanishni boshlagan xodimlar muqarrar ravishda yangi savollar va vaziyatlarga duch keladi.')),
            ('p', X('Local FSR support helps bridge this transition.', 'Местная поддержка FSR помогает пройти этот переходный этап.', 'Mahalliy FSR yordami bu o‘tish davrini bosib o‘tishga ko‘maklashadi.')),
            ('p', X('Instead of knowledge transfer ending when a training program is completed, it can continue through practical interaction between the FSR and customer personnel.',
                    'Передача знаний не заканчивается вместе с программой обучения — она продолжается в ходе практического взаимодействия FSR с персоналом заказчика.',
                    'Bilim uzatish o‘quv dasturi tugashi bilan to‘xtamaydi — u FSR va buyurtmachi xodimlari o‘rtasidagi amaliy hamkorlik orqali davom etadi.')),
            ('p', X('This creates a continuous capability-development process:', 'Так формируется непрерывный процесс развития компетенций:', 'Shu tariqa salohiyatni rivojlantirishning uzluksiz jarayoni shakllanadi:')),
            ('flow', [
                X('Training', 'Обучение', 'O‘qitish'),
                X('Practical Use', 'Практическое применение', 'Amaliy foydalanish'),
                X('FSR Support', 'Поддержка FSR', 'FSR yordami'),
                X('Knowledge Sharing', 'Обмен знаниями', 'Bilim almashish'),
                X('Greater Independence', 'Большая самостоятельность', 'Ko‘proq mustaqillik'),
            ]),
            ('p', X('Over time, customer personnel develop greater confidence and technical competence while maintaining access to specialist assistance when required.',
                    'Со временем персонал заказчика становится увереннее и компетентнее, сохраняя при этом доступ к помощи специалистов, когда она нужна.',
                    'Vaqt o‘tishi bilan buyurtmachi xodimlarining ishonchi va texnik malakasi oshadi, zarur bo‘lganda esa mutaxassislar yordamidan foydalanish imkoniyati saqlanib qoladi.')),
        ]}),
        ('prose', {'title': X('Building Local Capability', 'Развитие местных компетенций', 'Mahalliy salohiyatni rivojlantirish'), 'items': [
            ('p', X('The objective of FSR support is not to create permanent dependence on an external specialist.',
                    'Цель поддержки FSR — не создать постоянную зависимость от внешнего специалиста.',
                    'FSR yordamining maqsadi tashqi mutaxassisga doimiy qaramlik yaratish emas.')),
            ('p', X('Our approach is designed to strengthen the customer\'s own technical capability.',
                           'Наш подход направлен на укрепление собственных технических компетенций заказчика.',
                           'Yondashuvimiz buyurtmachining o‘z texnik salohiyatini mustahkamlashga qaratilgan.')),
            ('p', X('Through troubleshooting performed together with customer specialists, explanation of technical decisions, practical demonstrations, configuration support, and continuous knowledge sharing, the FSR helps local personnel develop deeper expertise.',
                    'Совместное со специалистами заказчика устранение неисправностей, объяснение технических решений, практические демонстрации, помощь в настройке и постоянный обмен знаниями — так FSR помогает местному персоналу углублять экспертизу.',
                    'Buyurtmachi mutaxassislari bilan birgalikda nosozliklarni bartaraf etish, texnik qarorlarni tushuntirish, amaliy namoyishlar, sozlashda ko‘maklashish va doimiy bilim almashish orqali FSR mahalliy xodimlarga chuqurroq ekspertizani rivojlantirishda yordam beradi.')),
            ('p', X('As customer capability grows, routine activities can increasingly be handled internally, while S3 and its partners remain available for more complex technical requirements.',
                    'По мере роста компетенций заказчика всё больше рутинных задач решается своими силами, а S3 и её партнёры остаются доступны для более сложных технических задач.',
                    'Buyurtmachi salohiyati oshgani sari odatiy vazifalar tobora ko‘proq ichki kuchlar bilan hal qilinadi, S3 va uning hamkorlari esa murakkabroq texnik talablar uchun doim tayyor bo‘ladi.')),
            ('p', X('This supports a sustainable transition from:', 'Это обеспечивает устойчивый переход:', 'Bu quyidagi barqaror o‘tishni ta’minlaydi:')),
            ('flow', [
                X('External Expertise', 'Внешняя экспертиза', 'Tashqi ekspertiza'),
                X('Shared Expertise', 'Совместная экспертиза', 'Umumiy ekspertiza'),
                X('Stronger Local Capability', 'Более сильные местные компетенции', 'Kuchliroq mahalliy salohiyat'),
            ]),
        ]}),
        ('prose', {'title': X('Lifecycle Support', 'Поддержка жизненного цикла', 'Hayotiy sikl davomida qo‘llab-quvvatlash'), 'soft': True, 'items': [
            ('p', X('FSR services form part of a broader S3 lifecycle support approach.',
                    'Услуги FSR — часть более широкого подхода S3 к поддержке жизненного цикла.',
                    'FSR xizmatlari S3 ning hayotiy sikl davomida qo‘llab-quvvatlash bo‘yicha kengroq yondashuvining bir qismidir.')),
            ('p', X('Depending on customer requirements and the technologies involved, support can include:',
                    'В зависимости от требований заказчика и используемых технологий поддержка может включать:',
                    'Buyurtmachi talablari va qo‘llanilayotgan texnologiyalarga qarab qo‘llab-quvvatlash quyidagilarni o‘z ichiga olishi mumkin:')),
            ('list', [
                X('Technical assistance', 'Техническую помощь', 'Texnik yordam'),
                X('Remote and on-site troubleshooting', 'Дистанционное устранение неисправностей и на месте', 'Masofadan va joyida nosozliklarni bartaraf etish'),
                X('System configuration support', 'Помощь в настройке систем', 'Tizimlarni sozlashda ko‘maklashish'),
                X('Software and firmware support', 'Поддержку программного обеспечения и прошивок', 'Dasturiy ta’minot va proshivkalarni qo‘llab-quvvatlash'),
                X('Integration assistance', 'Помощь в интеграции', 'Integratsiyada ko‘maklashish'),
                X('Preventive support activities', 'Профилактические мероприятия', 'Profilaktik tadbirlar'),
                X('Coordination of repairs and technical services', 'Координацию ремонта и технического обслуживания', 'Ta’mirlash va texnik xizmatlarni muvofiqlashtirish'),
                X('Manufacturer support coordination', 'Взаимодействие с поддержкой производителя', 'Ishlab chiqaruvchi yordamini muvofiqlashtirish'),
                X('Additional and refresher training', 'Дополнительное обучение и повышение квалификации', 'Qo‘shimcha o‘qitish va malaka oshirish'),
                X('Knowledge transfer', 'Передачу знаний', 'Bilim uzatish'),
                X('System expansion and modernization support', 'Поддержку расширения и модернизации систем', 'Tizimlarni kengaytirish va modernizatsiya qilishni qo‘llab-quvvatlash'),
                X('Field Service Representative services', 'Услуги выездных технических специалистов (FSR)', 'Joylardagi texnik vakillar (FSR) xizmatlari'),
            ]),
            ('p', X('Support arrangements can be adapted to the complexity of the solution, customer requirements, available internal expertise, and required level of local presence.',
                    'Формат поддержки может адаптироваться к сложности решения, требованиям заказчика, имеющейся внутренней экспертизе и необходимому уровню местного присутствия.',
                    'Qo‘llab-quvvatlash shartlari yechimning murakkabligi, buyurtmachi talablari, mavjud ichki ekspertiza va mahalliy vakillikning zarur darajasiga moslashtirilishi mumkin.')),
        ]}),
        ('cards', {
            'title': X('Direct Access to the Right Expertise', 'Прямой доступ к нужной экспертизе', 'Kerakli ekspertizaga bevosita kirish'),
            'columns': 'two',
            'intro': [
                ('p', X('Not every technical issue can or should be resolved at the same level.',
                        'Не каждый технический вопрос можно или нужно решать на одном и том же уровне.',
                        'Har bir texnik masalani bir xil darajada hal qilish mumkin ham emas, shart ham emas.')),
                ('p', X('S3 uses a structured support approach that allows issues to be addressed by the appropriate source of expertise.',
                        'S3 использует структурированный подход к поддержке, при котором каждый вопрос решается на соответствующем уровне экспертизы.',
                        'S3 har bir masala tegishli ekspertiza manbasi tomonidan hal qilinishiga imkon beradigan tizimli qo‘llab-quvvatlash yondashuvidan foydalanadi.')),
            ],
            'cards': [
                (X('Customer Level', 'Уровень заказчика', 'Buyurtmachi darajasi'), [
                    X('Trained operators, administrators, and technical personnel address tasks within their areas of responsibility.',
                      'Обученные операторы, администраторы и технический персонал решают задачи в пределах своей зоны ответственности.',
                      'O‘qitilgan operatorlar, administratorlar va texnik xodimlar o‘z mas’uliyat doirasidagi vazifalarni hal qiladi.')]),
                (X('FSR / Local Support Level', 'Уровень FSR / местной поддержки', 'FSR / mahalliy yordam darajasi'), [
                    X('Local specialists assist with troubleshooting, configuration, technical questions, and knowledge transfer.',
                      'Местные специалисты помогают с устранением неисправностей, настройкой, техническими вопросами и передачей знаний.',
                      'Mahalliy mutaxassislar nosozliklarni bartaraf etish, sozlash, texnik savollar va bilim uzatishda yordam beradi.')]),
                (X('S3 / Integration Level', 'Уровень S3 / интеграции', 'S3 / integratsiya darajasi'), [
                    X('S3 specialists address integration issues, solution-level questions, and coordination between different technologies.',
                      'Специалисты S3 решают вопросы интеграции, вопросы уровня всего решения и обеспечивают координацию между различными технологиями.',
                      'S3 mutaxassislari integratsiya masalalari, butun yechim darajasidagi savollar va turli texnologiyalar o‘rtasidagi muvofiqlashtirish bilan shug‘ullanadi.')]),
                (X('Partner / Vendor Level', 'Уровень партнёра / производителя', 'Hamkor / ishlab chiqaruvchi darajasi'), [
                    X('Specialized technical matters can be coordinated with integration partners and technology manufacturers when deeper product or engineering expertise is required.',
                      'Специализированные технические вопросы решаются совместно с партнёрами по интеграции и производителями технологий, когда требуется более глубокая продуктовая или инженерная экспертиза.',
                      'Mahsulot yoki muhandislik bo‘yicha chuqurroq ekspertiza talab qilinganda ixtisoslashgan texnik masalalar integratsiya bo‘yicha hamkorlar va texnologiya ishlab chiqaruvchilari bilan muvofiqlashtiriladi.')]),
            ],
            'outro': [
                ('p', X('This approach helps provide efficient support while ensuring that complex issues can reach the specialists best equipped to address them.',
                        'Такой подход обеспечивает эффективную поддержку и гарантирует, что сложные вопросы попадут к специалистам, лучше всего подготовленным для их решения.',
                        'Bu yondashuv samarali qo‘llab-quvvatlashni ta’minlaydi va murakkab masalalar ularni hal qilishga eng tayyor mutaxassislarga yetib borishini kafolatlaydi.')),
            ],
        }),
        ('prose', {'title': X('Support Through Partnership', 'Поддержка через партнёрство', 'Hamkorlik orqali qo‘llab-quvvatlash'), 'soft': True, 'items': [
            ('p', X('S3 does not operate in isolation.', 'S3 не работает в одиночку.', 'S3 yakkalikda ishlamaydi.')),
            ('p', X('Our support model is strengthened by cooperation with our technology and integration partners, providing access to specialized knowledge when required.',
                    'Нашу модель поддержки усиливает сотрудничество с технологическими партнёрами и партнёрами по интеграции, открывающее доступ к специализированным знаниям, когда они нужны.',
                    'Qo‘llab-quvvatlash modelimiz texnologik va integratsiya bo‘yicha hamkorlarimiz bilan hamkorlik orqali mustahkamlanadi, bu esa zarur bo‘lganda ixtisoslashgan bilimlardan foydalanish imkonini beradi.')),
            ('p', X('For solutions involving partner technologies, S3 can coordinate technical matters with the relevant organizations while remaining the customer\'s local point of engagement.',
                    'Для решений на основе технологий партнёров S3 координирует технические вопросы с соответствующими организациями, оставаясь для заказчика местной точкой взаимодействия.',
                    'Hamkorlar texnologiyalari asosidagi yechimlar uchun S3 texnik masalalarni tegishli tashkilotlar bilan muvofiqlashtiradi va buyurtmachi uchun mahalliy aloqa nuqtasi bo‘lib qoladi.')),
            ('p', X('This combination provides customers with the advantages of both local responsiveness and international expertise.',
                    'Такое сочетание даёт заказчикам преимущества и оперативной местной поддержки, и международной экспертизы.',
                    'Bu uyg‘unlik buyurtmachilarga ham tezkor mahalliy yordam, ham xalqaro ekspertiza afzalliklarini beradi.')),
        ]}),
        ('prose', {'title': X('We Stay Engaged', 'Мы остаёмся рядом', 'Biz doim yoningizdamiz'), 'items': [
            ('p', X('Delivery is not the end of our involvement.', 'Поставка — не конец нашего участия.', 'Yetkazib berish ishtirokimizning oxiri emas.')),
            ('p', X('From initial deployment and training to day-to-day technical assistance, troubleshooting, knowledge transfer, system development, and future modernization, S3 can remain engaged throughout the operational lifecycle of the solutions we provide.',
                    'От первоначального развёртывания и обучения до повседневной технической помощи, устранения неисправностей, передачи знаний, развития системы и будущей модернизации — S3 может оставаться рядом на протяжении всего жизненного цикла эксплуатации предоставленных решений.',
                    'Dastlabki joriy etish va o‘qitishdan tortib kundalik texnik yordam, nosozliklarni bartaraf etish, bilim uzatish, tizimni rivojlantirish va kelgusidagi modernizatsiyagacha — S3 taqdim etgan yechimlarining butun foydalanish davri mobaynida ishtirok etishda davom etishi mumkin.')),
            ('p', X('Our goal is straightforward:', 'Наша цель проста:', 'Maqsadimiz oddiy:')),
            ('p', X('Keep systems effective. Develop local expertise. Support long-term capability.',
                           'Поддерживать эффективность систем. Развивать местную экспертизу. Обеспечивать долгосрочные возможности.',
                           'Tizimlar samaradorligini saqlash. Mahalliy ekspertizani rivojlantirish. Uzoq muddatli salohiyatni qo‘llab-quvvatlash.')),
        ]}),
        ('closing', {'style': 'statement', 'statement': BRAND_STATEMENT, 'lines': [
            X('Local Presence. International Expertise.', 'Местное присутствие. Международная экспертиза.', 'Mahalliy vakillik. Xalqaro ekspertiza.'),
        ], 'buttons': [
            (TRAINING, 'training.html', 'primary-link'),
            (CONTACT_S3, 'contact.html', 'text-link'),
        ]}),
    ],
}
