from . import X, BRAND_STATEMENT, EXPLORE_SOLUTIONS, TRAINING

PAGE = {
    'slug': 'systems-integration.html',
    'title': X('Systems Integration', 'Системная интеграция', 'Tizim integratsiyasi'),
    'image': 'engineering-workshop.webp',
    'hero': {
        'title': X('From Technology to Operational Capability', 'От технологий — к операционным возможностям', 'Texnologiyadan — operatsion imkoniyatgacha'),
        'lead': X('Modern mission-critical environments depend on multiple technologies, systems, networks, platforms, and applications working together reliably and securely.',
                  'Современные критически важные операции зависят от того, насколько надёжно и безопасно работают вместе множество технологий, систем, сетей, платформ и приложений.',
                  'Zamonaviy o‘ta muhim operatsiyalar ko‘plab texnologiyalar, tizimlar, tarmoqlar, platformalar va ilovalarning birgalikda ishonchli va xavfsiz ishlashiga bog‘liq.'),
    },
    'blocks': [
        ('intro', {'items': [
            ('p', X('Systems integration is at the core of what S3 does.', 'Системная интеграция — основа деятельности S3.', 'Tizim integratsiyasi — S3 faoliyatining asosi.')),
            ('p', X('We work with our customers and technology partners to bring individual technologies together into complete solutions designed around operational requirements, existing capabilities, infrastructure, and future development needs.',
                    'Вместе с заказчиками и технологическими партнёрами мы объединяем отдельные технологии в законченные решения, построенные с учётом операционных требований, существующих возможностей, инфраструктуры и планов дальнейшего развития.',
                    'Buyurtmachilarimiz va texnologik hamkorlarimiz bilan birgalikda alohida texnologiyalarni operatsion talablar, mavjud imkoniyatlar, infratuzilma va kelgusidagi rivojlanish ehtiyojlari asosida yaratilgan yaxlit yechimlarga birlashtiramiz.')),
            ('p', X('Our role goes beyond supplying individual products. We help determine how technologies should connect, exchange information, and operate together as part of a wider operational environment.',
                    'Наша роль не ограничивается поставкой отдельных продуктов. Мы помогаем определить, как технологии должны соединяться, обмениваться информацией и работать вместе в составе более широкой операционной среды.',
                    'Bizning vazifamiz alohida mahsulotlarni yetkazib berish bilan cheklanmaydi. Biz texnologiyalar kengroq operatsion muhit tarkibida qanday ulanishi, axborot almashishi va birgalikda ishlashi kerakligini aniqlashga yordam beramiz.')),
            ('p', X('The objective is to transform individual technologies into integrated, sustainable operational capabilities.',
                    'Цель — превратить отдельные технологии в интегрированные и устойчивые операционные возможности.',
                    'Maqsad — alohida texnologiyalarni integratsiyalashgan va barqaror operatsion imkoniyatlarga aylantirish.')),
        ]}),
        ('cards', {
            'title': X('Modernization Without Starting From Zero', 'Модернизация без начала с нуля', 'Noldan boshlamasdan modernizatsiya'),
            'soft': True,
            'intro': [
                ('p', X('Organizations often already have significant investments in communications systems, networks, applications, platforms, infrastructure, and — equally importantly — personnel trained to operate and support them.',
                        'Организации зачастую уже вложили значительные средства в системы связи, сети, приложения, платформы, инфраструктуру и — что не менее важно — в персонал, обученный их эксплуатировать и поддерживать.',
                        'Tashkilotlar ko‘pincha aloqa tizimlari, tarmoqlar, ilovalar, platformalar, infratuzilma va — bundan kam muhim bo‘lmagan — ulardan foydalanish va ularni qo‘llab-quvvatlashga o‘qitilgan xodimlarga katta mablag‘ sarflagan bo‘ladi.')),
                ('p', X('Modernization does not necessarily mean replacing everything.', 'Модернизация не обязательно означает замену всего.', 'Modernizatsiya hamma narsani almashtirish degani emas.')),
                ('p', X('Where technically feasible and operationally appropriate, S3 works to integrate new technologies and capabilities with the customer\'s existing systems, networks, platforms, and infrastructure.',
                        'Там, где это технически возможно и оправдано с операционной точки зрения, S3 интегрирует новые технологии и возможности с существующими системами, сетями, платформами и инфраструктурой заказчика.',
                        'Texnik jihatdan mumkin va operatsion jihatdan maqsadga muvofiq bo‘lgan hollarda S3 yangi texnologiyalar va imkoniyatlarni buyurtmachining mavjud tizimlari, tarmoqlari, platformalari va infratuzilmasi bilan integratsiya qiladi.')),
                ('p', X('Our approach is designed to preserve valuable existing capabilities while progressively introducing technologies that can improve performance, interoperability, security, situational awareness, and operational effectiveness.',
                        'Наш подход позволяет сохранить ценные существующие возможности и поэтапно внедрять технологии, повышающие производительность, совместимость, безопасность, ситуационную осведомлённость и операционную эффективность.',
                        'Yondashuvimiz qimmatli mavjud imkoniyatlarni saqlab qolgan holda samaradorlik, o‘zaro moslik, xavfsizlik, vaziyatdan xabardorlik va operatsion samaradorlikni oshiradigan texnologiyalarni bosqichma-bosqich joriy etishga qaratilgan.')),
                ('p', X('This approach can help customers:', 'Такой подход помогает заказчикам:', 'Bu yondashuv buyurtmachilarga quyidagilarda yordam beradi:')),
            ],
            'cards': [
                (X('Protect existing investments', 'Сохранить сделанные инвестиции', 'Mavjud investitsiyalarni saqlash'), [
                    X('By retaining systems and infrastructure that continue to provide operational value.', 'Сохраняя системы и инфраструктуру, которые продолжают приносить операционную пользу.', 'Operatsion foyda keltirishda davom etayotgan tizimlar va infratuzilmani saqlab qolish orqali.')]),
                (X('Introduce new capabilities progressively', 'Внедрять новые возможности поэтапно', 'Yangi imkoniyatlarni bosqichma-bosqich joriy etish'), [
                    X('Rather than requiring complete technology replacement at once.', 'Без необходимости единовременной полной замены технологий.', 'Texnologiyalarni birdaniga to‘liq almashtirishni talab qilmasdan.')]),
                (X('Improve interoperability', 'Улучшить совместимость', 'O‘zaro moslikni yaxshilash'), [
                    X('Between new and existing systems.', 'Между новыми и существующими системами.', 'Yangi va mavjud tizimlar o‘rtasida.')]),
                (X('Reduce unnecessary replacement', 'Сократить ненужную замену', 'Keraksiz almashtirishlarni kamaytirish'), [
                    X('Of operational equipment and infrastructure.', 'Эксплуатируемого оборудования и инфраструктуры.', 'Foydalanilayotgan uskunalar va infratuzilmani.')]),
                (X('Simplify transition', 'Упростить переход', 'O‘tishni soddalashtirish'), [
                    X('By allowing technology, processes, and personnel to evolve together.', 'Позволяя технологиям, процессам и персоналу развиваться вместе.', 'Texnologiyalar, jarayonlar va xodimlarning birgalikda rivojlanishiga imkon berish orqali.')]),
                (X('Create a foundation for future modernization', 'Заложить основу для будущей модернизации', 'Kelajakdagi modernizatsiya uchun poydevor yaratish'), [
                    X('Through architectures designed to accommodate further development.', 'С помощью архитектур, рассчитанных на дальнейшее развитие.', 'Keyingi rivojlanishga mo‘ljallangan arxitekturalar orqali.')]),
            ],
            'outro': [
                ('p', X('Modernization is also about people. Existing knowledge, experience, procedures, and trained personnel are valuable organizational assets.',
                        'Модернизация — это ещё и люди. Имеющиеся знания, опыт, процедуры и обученный персонал — ценные активы организации.',
                        'Modernizatsiya — bu odamlar hamdir. Mavjud bilimlar, tajriba, tartib-qoidalar va o‘qitilgan xodimlar tashkilotning qimmatli boyligidir.')),
                ('p', X('For this reason, S3 combines systems integration with training, knowledge transfer, and lifecycle support, helping customers introduce new capabilities while building on the expertise they already have.',
                        'Поэтому S3 сочетает системную интеграцию с обучением, передачей знаний и поддержкой жизненного цикла, помогая заказчикам внедрять новые возможности, опираясь на уже имеющуюся экспертизу.',
                        'Shu sababli S3 tizim integratsiyasini o‘qitish, bilim uzatish va hayotiy sikl davomida qo‘llab-quvvatlash bilan uyg‘unlashtirib, buyurtmachilarga mavjud tajribasiga tayangan holda yangi imkoniyatlarni joriy etishda yordam beradi.')),
                ('p', X('Preserving what works. Integrating what is new. Building for what comes next.',
                               'Сохраняем то, что работает. Интегрируем новое. Создаём основу для будущего.',
                               'Ishlayotganini saqlaymiz. Yangisini integratsiya qilamiz. Kelajak uchun asos yaratamiz.')),
            ],
        }),
        ('prose', {'title': X('Integration Starts With the Requirement', 'Интеграция начинается с требований', 'Integratsiya talabdan boshlanadi'), 'items': [
            ('p', X('Successful integration begins with understanding the operational requirement — not with selecting a product.',
                    'Успешная интеграция начинается с понимания операционной задачи, а не с выбора продукта.',
                    'Muvaffaqiyatli integratsiya mahsulot tanlashdan emas, balki operatsion talabni tushunishdan boshlanadi.')),
            ('p', X('Before proposing a solution, S3 works to understand the customer\'s objectives, existing capabilities, technical environment, operational constraints, interoperability requirements, and future development plans.',
                    'Прежде чем предложить решение, S3 изучает цели заказчика, существующие возможности, техническую среду, операционные ограничения, требования к совместимости и планы дальнейшего развития.',
                    'Yechim taklif qilishdan oldin S3 buyurtmachining maqsadlari, mavjud imkoniyatlari, texnik muhiti, operatsion cheklovlari, o‘zaro moslik talablari va kelgusidagi rivojlanish rejalarini o‘rganadi.')),
            ('p', X('This allows us to answer three fundamental questions:', 'Это позволяет ответить на три ключевых вопроса:', 'Bu bizga uchta asosiy savolga javob berish imkonini beradi:')),
            ('questions', [
                X('What capability is required?', 'Какая возможность необходима?', 'Qanday imkoniyat kerak?'),
                X('What existing capabilities should be retained?', 'Какие существующие возможности следует сохранить?', 'Mavjud imkoniyatlardan qaysilarini saqlab qolish kerak?'),
                X('How should new and existing technologies work together?', 'Как новые и существующие технологии должны работать вместе?', 'Yangi va mavjud texnologiyalar qanday birgalikda ishlashi kerak?'),
            ]),
            ('p', X('Only then can the appropriate technologies and integration approach be defined.',
                    'Только после этого можно определить подходящие технологии и подход к интеграции.',
                    'Faqat shundan keyin mos texnologiyalar va integratsiya yondashuvini belgilash mumkin.')),
            ('p', X('This requirements-driven approach helps ensure that technology is selected to support an operational objective rather than requiring the customer to adapt its requirements to a particular product.',
                    'Такой подход, основанный на требованиях, гарантирует, что технология выбирается для решения операционной задачи, а не заказчику приходится подстраивать свои требования под конкретный продукт.',
                    'Talablarga asoslangan bu yondashuv texnologiyaning operatsion maqsadga xizmat qilishi uchun tanlanishini ta’minlaydi, buyurtmachidan esa o‘z talablarini muayyan mahsulotga moslashtirish talab qilinmaydi.')),
        ]}),
        ('prose', {'title': X('Bringing Systems Together', 'Объединяем системы', 'Tizimlarni birlashtiramiz'), 'soft': True, 'items': [
            ('p', X('Depending on the project, S3 can integrate technologies across multiple capability areas, including:',
                    'В зависимости от проекта S3 может интегрировать технологии из разных областей, включая:',
                    'Loyihaga qarab S3 turli yo‘nalishlardagi texnologiyalarni integratsiya qila oladi, jumladan:')),
            ('list', [
                X('Secure tactical communications', 'Защищённая тактическая связь', 'Himoyalangan taktik aloqa'),
                X('Command and Control (C2)', 'Командование и управление (C2)', 'Qo‘mondonlik va boshqaruv (C2)'),
                X('Tactical data networks', 'Тактические сети передачи данных', 'Taktik ma’lumot uzatish tarmoqlari'),
                X('Fire Support and Targeting Systems', 'Системы огневой поддержки и целеуказания', 'O‘t bilan qo‘llab-quvvatlash va nishon ko‘rsatish tizimlari'),
                X('SATCOM', 'Спутниковая связь (SATCOM)', 'Sun’iy yo‘ldosh aloqasi (SATCOM)'),
                X('ISR solutions', 'Решения ISR', 'ISR yechimlari'),
                X('UAV systems and information feeds', 'Системы БПЛА и потоки данных от них', 'UAV tizimlari va ulardan keladigan axborot oqimlari'),
                X('Command-post infrastructure', 'Инфраструктура командных пунктов', 'Qo‘mondonlik punktlari infratuzilmasi'),
                X('IT and network infrastructure', 'ИТ- и сетевая инфраструктура', 'AT va tarmoq infratuzilmasi'),
                X('Cybersecurity technologies', 'Технологии кибербезопасности', 'Kiberxavfsizlik texnologiyalari'),
                X('Electronic Warfare capabilities', 'Средства радиоэлектронной борьбы', 'Radioelektron kurash vositalari'),
                X('Mobile and deployable communication systems', 'Мобильные и развёртываемые системы связи', 'Mobil va joylashtiriladigan aloqa tizimlari'),
                X('Existing customer systems and operational platforms', 'Существующие системы и операционные платформы заказчика', 'Buyurtmachining mavjud tizimlari va operatsion platformalari'),
            ]),
            ('p', X('These technologies may come from different sources and serve different functions, but their operational value increases when they can securely exchange information and operate as part of a coordinated environment.',
                    'Эти технологии могут происходить из разных источников и выполнять разные функции, но их операционная ценность возрастает, когда они могут безопасно обмениваться информацией и работать в составе согласованной среды.',
                    'Bu texnologiyalar turli manbalardan kelib, turli vazifalarni bajarishi mumkin, biroq ular xavfsiz axborot almasha olsa va muvofiqlashtirilgan muhit tarkibida ishlasa, ularning operatsion qiymati oshadi.')),
        ]}),
        ('cards', {
            'title': X('Interoperability by Design', 'Совместимость, заложенная в проект', 'Loyihaning o‘zida o‘zaro moslik'),
            'subtitle': X('Connecting People, Systems, and Information', 'Связываем людей, системы и информацию', 'Odamlar, tizimlar va axborotni bog‘laymiz'),
            'intro': [
                ('p', X('Interoperability is a fundamental consideration in modern operational environments.',
                        'Совместимость — одно из ключевых условий в современной операционной среде.',
                        'O‘zaro moslik zamonaviy operatsion muhitning asosiy shartlaridan biridir.')),
                ('p', X('Communications systems must connect users. Networks must transport information. C2 applications must provide relevant information to decision-makers. Command posts must communicate with deployed personnel and platforms. Sensors and other information sources must make useful information available to authorized users.',
                        'Системы связи должны соединять пользователей. Сети должны передавать информацию. Приложения C2 должны предоставлять нужную информацию тем, кто принимает решения. Командные пункты должны поддерживать связь с развёрнутым персоналом и платформами. Датчики и другие источники должны делать полезную информацию доступной авторизованным пользователям.',
                        'Aloqa tizimlari foydalanuvchilarni bog‘lashi kerak. Tarmoqlar axborotni uzatishi kerak. C2 ilovalari qaror qabul qiluvchilarga kerakli axborotni yetkazishi kerak. Qo‘mondonlik punktlari joylashtirilgan xodimlar va platformalar bilan aloqada bo‘lishi kerak. Sensorlar va boshqa axborot manbalari foydali axborotni vakolatli foydalanuvchilarga taqdim etishi kerak.')),
                ('p', X('S3 considers these relationships from the beginning of the solution design process.',
                        'S3 учитывает эти взаимосвязи с самого начала проектирования решения.',
                        'S3 bu o‘zaro bog‘liqliklarni yechimni loyihalashning boshidanoq hisobga oladi.')),
                ('p', X('Depending on customer requirements, integration may include:', 'В зависимости от требований заказчика интеграция может включать:', 'Buyurtmachi talablariga qarab integratsiya quyidagilarni o‘z ichiga olishi mumkin:')),
            ],
            'cards': [
                (X('Communications Integration', 'Интеграция связи', 'Aloqa integratsiyasi'), [
                    X('Connecting users, radio networks, communication systems, and operational locations.', 'Соединение пользователей, радиосетей, систем связи и пунктов выполнения задач.', 'Foydalanuvchilar, radiotarmoqlar, aloqa tizimlari va operatsion joylarni bog‘lash.')]),
                (X('Network Integration', 'Сетевая интеграция', 'Tarmoq integratsiyasi'), [
                    X('Establishing secure data connectivity between systems, platforms, command posts, and applications.', 'Организация защищённой передачи данных между системами, платформами, командными пунктами и приложениями.', 'Tizimlar, platformalar, qo‘mondonlik punktlari va ilovalar o‘rtasida himoyalangan ma’lumot almashinuvini yo‘lga qo‘yish.')]),
                (X('C2 Integration', 'Интеграция C2', 'C2 integratsiyasi'), [
                    X('Connecting command-and-control applications with tactical communications, networks, and relevant information sources.', 'Подключение приложений командования и управления к тактической связи, сетям и соответствующим источникам информации.', 'Qo‘mondonlik va boshqaruv ilovalarini taktik aloqa, tarmoqlar va tegishli axborot manbalari bilan bog‘lash.')]),
                (X('Platform Integration', 'Интеграция с платформами', 'Platformalar bilan integratsiya'), [
                    X('Integrating communications, networking, C2, and other technologies with mobile, fixed, or deployable platforms.', 'Интеграция связи, сетей, C2 и других технологий с мобильными, стационарными или развёртываемыми платформами.', 'Aloqa, tarmoq, C2 va boshqa texnologiyalarni mobil, statsionar yoki joylashtiriladigan platformalar bilan integratsiya qilish.')]),
                (X('Information Integration', 'Информационная интеграция', 'Axborot integratsiyasi'), [
                    X('Supporting controlled information exchange between compatible operational systems.', 'Обеспечение контролируемого обмена информацией между совместимыми операционными системами.', 'Mos operatsion tizimlar o‘rtasida nazorat qilinadigan axborot almashinuvini ta’minlash.')]),
                (X('Infrastructure Integration', 'Интеграция инфраструктуры', 'Infratuzilma integratsiyasi'), [
                    X('Bringing together communications, IT, networking, power, workstations, servers, displays, and other supporting technologies within command-post or deployable environments.', 'Объединение связи, ИТ, сетей, электропитания, рабочих мест, серверов, дисплеев и других вспомогательных технологий в среде командных пунктов или развёртываемых комплексов.', 'Qo‘mondonlik punktlari yoki joylashtiriladigan muhitda aloqa, AT, tarmoqlar, elektr ta’minoti, ish o‘rinlari, serverlar, displeylar va boshqa yordamchi texnologiyalarni birlashtirish.')]),
            ],
            'outro': [
                ('p', X('The objective is not connectivity for its own sake, but the reliable delivery of the right information to the right users and systems when it is needed.',
                               'Цель — не связь ради связи, а надёжная доставка нужной информации нужным пользователям и системам в нужный момент.',
                               'Maqsad — aloqaning o‘zi emas, balki kerakli axborotni kerakli foydalanuvchilar va tizimlarga kerakli vaqtda ishonchli yetkazish.')),
            ],
        }),
        ('details', {
            'title': X('Our Integration Process', 'Наш процесс интеграции', 'Bizning integratsiya jarayonimiz'),
            'rows': [
                {'title': X('1. Understand', '1. Понимание', '1. Tushunish'), 'items': [
                    ('p', X('We begin by working with the customer to understand operational objectives, existing capabilities, constraints, technical dependencies, and expected outcomes.',
                            'Мы начинаем с совместной работы с заказчиком, чтобы понять операционные цели, существующие возможности, ограничения, технические зависимости и ожидаемые результаты.',
                            'Ishni buyurtmachi bilan birgalikda operatsion maqsadlar, mavjud imkoniyatlar, cheklovlar, texnik bog‘liqliklar va kutilayotgan natijalarni tushunishdan boshlaymiz.'))]},
                {'title': X('2. Assess', '2. Оценка', '2. Baholash'), 'items': [
                    ('p', X('Where existing systems are involved, we assess the relevant technical environment, including infrastructure, interfaces, networks, applications, and interoperability requirements.',
                            'Если задействованы существующие системы, мы оцениваем соответствующую техническую среду: инфраструктуру, интерфейсы, сети, приложения и требования к совместимости.',
                            'Mavjud tizimlar ishtirok etgan hollarda tegishli texnik muhitni — infratuzilma, interfeyslar, tarmoqlar, ilovalar va o‘zaro moslik talablarini baholaymiz.'))]},
                {'title': X('3. Design', '3. Проектирование', '3. Loyihalash'), 'items': [
                    ('p', X('Working with our technology partners, S3 develops a solution architecture defining the technologies required and how individual components should interact.',
                            'Совместно с технологическими партнёрами S3 разрабатывает архитектуру решения, определяющую необходимые технологии и порядок взаимодействия отдельных компонентов.',
                            'Texnologik hamkorlarimiz bilan birgalikda S3 kerakli texnologiyalarni va alohida komponentlar qanday o‘zaro ishlashi kerakligini belgilaydigan yechim arxitekturasini ishlab chiqadi.')),
                    ('p', X('The design considers security, interoperability, reliability, scalability, maintainability, and future development.',
                            'Проект учитывает безопасность, совместимость, надёжность, масштабируемость, ремонтопригодность и дальнейшее развитие.',
                            'Loyiha xavfsizlik, o‘zaro moslik, ishonchlilik, kengaytiriluvchanlik, xizmat ko‘rsatish qulayligi va kelgusidagi rivojlanishni hisobga oladi.'))]},
                {'title': X('4. Integrate', '4. Интеграция', '4. Integratsiya qilish'), 'items': [
                    ('p', X('Selected technologies are configured and brought together according to the agreed solution architecture.',
                            'Выбранные технологии настраиваются и объединяются в соответствии с согласованной архитектурой решения.',
                            'Tanlangan texnologiyalar kelishilgan yechim arxitekturasiga muvofiq sozlanadi va birlashtiriladi.')),
                    ('p', X('Integration may involve communications systems, networks, applications, platforms, servers, command-post infrastructure, and existing customer systems.',
                            'Интеграция может охватывать системы связи, сети, приложения, платформы, серверы, инфраструктуру командных пунктов и существующие системы заказчика.',
                            'Integratsiya aloqa tizimlari, tarmoqlar, ilovalar, platformalar, serverlar, qo‘mondonlik punktlari infratuzilmasi va buyurtmachining mavjud tizimlarini qamrab olishi mumkin.'))]},
                {'title': X('5. Test & Validate', '5. Испытания и проверка', '5. Sinov va tasdiqlash'), 'items': [
                    ('p', X('Integration must work in practice.', 'Интеграция должна работать на практике.', 'Integratsiya amalda ishlashi kerak.')),
                    ('p', X('The solution is tested to verify functionality, connectivity, information exchange, and interoperability against the defined requirements.',
                            'Решение проходит испытания, подтверждающие функциональность, связность, обмен информацией и совместимость в соответствии с определёнными требованиями.',
                            'Yechim belgilangan talablarga muvofiq funksionallik, ulanish, axborot almashinuvi va o‘zaro moslikni tekshirish uchun sinovdan o‘tkaziladi.')),
                    ('p', X('Where appropriate, representative operational scenarios can be used to validate that the integrated solution performs as intended.',
                            'При необходимости для подтверждения того, что интегрированное решение работает как задумано, используются типовые операционные сценарии.',
                            'Zarur hollarda integratsiyalashgan yechim ko‘zda tutilganidek ishlashini tasdiqlash uchun namunaviy operatsion ssenariylardan foydalaniladi.'))]},
                {'title': X('6. Deploy', '6. Развёртывание', '6. Joriy etish'), 'items': [
                    ('p', X('Following successful integration and testing, S3 supports deployment, configuration, commissioning, and introduction of the solution into the customer\'s operational environment.',
                            'После успешной интеграции и испытаний S3 сопровождает развёртывание, настройку, ввод в эксплуатацию и внедрение решения в операционную среду заказчика.',
                            'Muvaffaqiyatli integratsiya va sinovlardan so‘ng S3 yechimni joriy etish, sozlash, foydalanishga topshirish va buyurtmachining operatsion muhitiga tatbiq qilishni qo‘llab-quvvatlaydi.'))]},
                {'title': X('7. Train', '7. Обучение', '7. O‘qitish'), 'items': [
                    ('p', X('Operators, administrators, technical personnel, maintenance specialists, and customer instructors can be trained according to their responsibilities.',
                            'Операторы, администраторы, технический персонал, специалисты по обслуживанию и инструкторы заказчика проходят обучение в соответствии со своими обязанностями.',
                            'Operatorlar, administratorlar, texnik xodimlar, xizmat ko‘rsatish mutaxassislari va buyurtmachi instruktorlari o‘z vazifalariga muvofiq o‘qitilishi mumkin.')),
                    ('p', X('Training helps customer personnel understand both the individual technologies and how they operate together as an integrated system.',
                            'Обучение помогает персоналу заказчика понять как отдельные технологии, так и то, как они работают вместе в составе интегрированной системы.',
                            'O‘qitish buyurtmachi xodimlariga alohida texnologiyalarni ham, ularning yagona integratsiyalashgan tizim sifatida qanday birgalikda ishlashini ham tushunishga yordam beradi.'))]},
                {'title': X('8. Support', '8. Поддержка', '8. Qo‘llab-quvvatlash'), 'items': [
                    ('p', X('Integration does not end with commissioning.', 'Интеграция не заканчивается вводом в эксплуатацию.', 'Integratsiya foydalanishga topshirish bilan tugamaydi.')),
                    ('p', X('S3 can continue supporting the solution through technical assistance, troubleshooting, configuration support, knowledge sharing, training, and Field Service Representative services.',
                            'S3 может и дальше поддерживать решение: оказывать техническую помощь, устранять неисправности, помогать с настройкой, делиться знаниями, обучать и предоставлять услуги выездных технических специалистов (FSR).',
                            'S3 yechimni texnik yordam, nosozliklarni bartaraf etish, sozlashda ko‘maklashish, bilim almashish, o‘qitish va joylardagi texnik vakillar (FSR) xizmatlari orqali qo‘llab-quvvatlashda davom etishi mumkin.'))]},
            ],
            'outro': [
                ('flow', [
                    X('Understand', 'Понимание', 'Tushunish'), X('Assess', 'Оценка', 'Baholash'), X('Design', 'Проектирование', 'Loyihalash'),
                    X('Integrate', 'Интеграция', 'Integratsiya'), X('Test', 'Испытания', 'Sinov'), X('Deploy', 'Развёртывание', 'Joriy etish'),
                    X('Train', 'Обучение', 'O‘qitish'), X('Support', 'Поддержка', 'Qo‘llab-quvvatlash'),
                ]),
            ],
        }),
        ('prose', {'title': X('Integration Through Partnership', 'Интеграция через партнёрство', 'Hamkorlik orqali integratsiya'), 'items': [
            ('p', X('Complex systems integration requires close cooperation between the customer, systems integrator, and technology manufacturers.',
                    'Сложная системная интеграция требует тесного взаимодействия заказчика, системного интегратора и производителей технологий.',
                    'Murakkab tizim integratsiyasi buyurtmachi, tizim integratori va texnologiya ishlab chiqaruvchilari o‘rtasida yaqin hamkorlikni talab qiladi.')),
            ('p', X('S3 serves as a local integration and coordination point, connecting customer requirements with the technologies and specialist expertise available through our international partners.',
                    'S3 выступает местным центром интеграции и координации, связывая требования заказчика с технологиями и экспертизой, доступными через наших международных партнёров.',
                    'S3 mahalliy integratsiya va muvofiqlashtirish markazi bo‘lib, buyurtmachi talablarini xalqaro hamkorlarimiz orqali mavjud texnologiyalar va mutaxassislar tajribasi bilan bog‘laydi.')),
            ('p', X('This approach enables direct cooperation between customer specialists, S3 engineers and representatives, and technology manufacturers when deeper technical expertise is required.',
                    'Такой подход обеспечивает прямое взаимодействие специалистов заказчика, инженеров и представителей S3 и производителей технологий, когда требуется более глубокая техническая экспертиза.',
                    'Bu yondashuv chuqurroq texnik ekspertiza talab qilinganda buyurtmachi mutaxassislari, S3 muhandislari va vakillari hamda texnologiya ishlab chiqaruvchilari o‘rtasida bevosita hamkorlik qilish imkonini beradi.')),
            ('p', X('It also allows S3 to remain close to the customer during implementation and operation while providing access to international technical resources.',
                    'Он также позволяет S3 оставаться рядом с заказчиком на этапах внедрения и эксплуатации, обеспечивая доступ к международным техническим ресурсам.',
                    'Shuningdek, u S3 ga joriy etish va foydalanish bosqichlarida buyurtmachiga yaqin bo‘lish va xalqaro texnik resurslardan foydalanish imkonini beradi.')),
            ('p', X('The result is a combination of global technology and expertise with local integration and support.',
                           'В результате мировые технологии и экспертиза сочетаются с местной интеграцией и поддержкой.',
                           'Natijada global texnologiyalar va ekspertiza mahalliy integratsiya va qo‘llab-quvvatlash bilan uyg‘unlashadi.')),
        ]}),
        ('prose', {'title': X('Integration Beyond Initial Deployment', 'Интеграция после первоначального развёртывания', 'Dastlabki joriy etishdan keyingi integratsiya'), 'soft': True, 'items': [
            ('p', X('Operational requirements change. Technologies evolve. New capabilities become available.',
                           'Операционные требования меняются. Технологии развиваются. Появляются новые возможности.',
                           'Operatsion talablar o‘zgaradi. Texnologiyalar rivojlanadi. Yangi imkoniyatlar paydo bo‘ladi.')),
            ('p', X('For this reason, systems integration should consider not only today\'s requirement but also what may be needed tomorrow.',
                    'Поэтому системная интеграция должна учитывать не только сегодняшние требования, но и то, что может понадобиться завтра.',
                    'Shu sababli tizim integratsiyasi nafaqat bugungi talabni, balki ertaga nima kerak bo‘lishi mumkinligini ham hisobga olishi kerak.')),
            ('p', X('Where possible, S3 promotes architectures that allow customers to introduce additional radios, applications, networks, platforms, sensors, and other technologies progressively rather than repeatedly rebuilding the entire environment.',
                    'По возможности S3 предлагает архитектуры, позволяющие заказчикам поэтапно добавлять радиостанции, приложения, сети, платформы, датчики и другие технологии, не перестраивая всю среду заново.',
                    'Imkon qadar S3 buyurtmachilarga butun muhitni qayta-qayta qurmasdan, qo‘shimcha radiostansiyalar, ilovalar, tarmoqlar, platformalar, sensorlar va boshqa texnologiyalarni bosqichma-bosqich qo‘shish imkonini beradigan arxitekturalarni taklif qiladi.')),
            ('p', X('This supports a transition from individual technology projects toward a connected, interoperable, and sustainable technology ecosystem.',
                    'Это способствует переходу от отдельных технологических проектов к связанной, совместимой и устойчивой технологической экосистеме.',
                    'Bu alohida texnologik loyihalardan o‘zaro bog‘langan, mos va barqaror texnologik ekotizimga o‘tishga yordam beradi.')),
        ]}),
        ('prose', {'title': X('Integration Supported by Knowledge', 'Интеграция, подкреплённая знаниями', 'Bilimga tayangan integratsiya'), 'items': [
            ('p', X('Technology integration and human capability must develop together.',
                           'Интеграция технологий и развитие людей должны идти рука об руку.',
                           'Texnologiyalar integratsiyasi va inson salohiyati birgalikda rivojlanishi kerak.')),
            ('p', X('Even the most advanced integrated system cannot deliver its full value if personnel do not understand how to operate, administer, maintain, and support it.',
                    'Даже самая совершенная интегрированная система не раскроет свой потенциал, если персонал не понимает, как её эксплуатировать, администрировать, обслуживать и поддерживать.',
                    'Hatto eng ilg‘or integratsiyalashgan tizim ham, agar xodimlar undan qanday foydalanish, uni boshqarish, unga xizmat ko‘rsatish va uni qo‘llab-quvvatlashni tushunmasa, o‘z qiymatini to‘liq namoyon eta olmaydi.')),
            ('p', X('Training and knowledge transfer are therefore an integral part of the S3 integration approach.',
                    'Поэтому обучение и передача знаний — неотъемлемая часть подхода S3 к интеграции.',
                    'Shuning uchun o‘qitish va bilim uzatish S3 integratsiya yondashuvining ajralmas qismidir.')),
            ('p', X('Depending on customer requirements, S3 provides training for:', 'В зависимости от требований заказчика S3 проводит обучение для:', 'Buyurtmachi talablariga qarab S3 quyidagilar uchun o‘qitish o‘tkazadi:')),
            ('list', [
                X('Operators', 'Операторов', 'Operatorlar'),
                X('System administrators', 'Системных администраторов', 'Tizim administratorlari'),
                X('Technical and maintenance personnel', 'Технического и обслуживающего персонала', 'Texnik va xizmat ko‘rsatuvchi xodimlar'),
                X('Customer instructors through Train-the-Trainer (ToT) programs', 'Инструкторов заказчика — по программам подготовки инструкторов (ToT)', 'Trenerlarni tayyorlash (ToT) dasturlari orqali buyurtmachi instruktorlari'),
            ]),
            ('p', X('Our objective is to develop customer personnel who understand their systems and can perform appropriate operational and technical tasks independently, while retaining access to S3 and manufacturer expertise when higher-level support is required.',
                    'Наша цель — подготовить персонал заказчика, который понимает свои системы и способен самостоятельно выполнять соответствующие операционные и технические задачи, сохраняя доступ к экспертизе S3 и производителей, когда нужна поддержка более высокого уровня.',
                    'Maqsadimiz — o‘z tizimlarini tushunadigan va tegishli operatsion hamda texnik vazifalarni mustaqil bajara oladigan buyurtmachi xodimlarini tayyorlash, shu bilan birga yuqori darajadagi yordam kerak bo‘lganda S3 va ishlab chiqaruvchilar ekspertizasidan foydalanish imkoniyatini saqlash.')),
        ]}),
        ('prose', {'title': X('Supported Throughout the Lifecycle', 'Поддержка на всём жизненном цикле', 'Butun hayotiy sikl davomida qo‘llab-quvvatlash'), 'soft': True, 'items': [
            ('p', X('Our involvement does not have to end when a system becomes operational.',
                    'Наше участие не обязательно заканчивается, когда система вводится в эксплуатацию.',
                    'Tizim ishga tushirilgach, ishtirokimiz tugashi shart emas.')),
            ('p', X('S3 can provide continued technical and operational support for the solutions we deliver, including Field Service Representative (FSR) support, troubleshooting, configuration assistance, knowledge sharing, additional training, and coordination with technology manufacturers.',
                    'S3 может оказывать постоянную техническую и эксплуатационную поддержку поставленных решений, включая работу выездных технических специалистов (FSR), устранение неисправностей, помощь в настройке, обмен знаниями, дополнительное обучение и взаимодействие с производителями технологий.',
                    'S3 yetkazib bergan yechimlari uchun doimiy texnik va operatsion yordam ko‘rsata oladi, jumladan joylardagi texnik vakillar (FSR) yordami, nosozliklarni bartaraf etish, sozlashda ko‘maklashish, bilim almashish, qo‘shimcha o‘qitish va texnologiya ishlab chiqaruvchilari bilan muvofiqlashtirish.')),
            ('p', X('This lifecycle approach helps customers maintain the effectiveness of their systems while continuously developing local technical expertise.',
                    'Такой подход помогает заказчикам поддерживать эффективность своих систем и постоянно развивать местную техническую экспертизу.',
                    'Bu yondashuv buyurtmachilarga o‘z tizimlarining samaradorligini saqlash va mahalliy texnik tajribani doimiy rivojlantirishda yordam beradi.')),
        ]}),
        ('prose', {'title': X('One Integrated Approach', 'Единый интегрированный подход', 'Yagona integratsiyalashgan yondashuv'), 'items': [
            ('p', X('S3 brings together technology, integration, people, and support.',
                           'S3 объединяет технологии, интеграцию, людей и поддержку.',
                           'S3 texnologiya, integratsiya, odamlar va qo‘llab-quvvatlashni birlashtiradi.')),
            ('p', X('From understanding the initial requirement to integrating new capabilities with existing systems, training customer personnel, and supporting deployed solutions, we provide a coordinated approach throughout the solution lifecycle.',
                    'От понимания исходной задачи до интеграции новых возможностей с существующими системами, обучения персонала заказчика и поддержки развёрнутых решений — мы обеспечиваем согласованный подход на протяжении всего жизненного цикла решения.',
                    'Dastlabki talabni tushunishdan tortib yangi imkoniyatlarni mavjud tizimlar bilan integratsiya qilish, buyurtmachi xodimlarini o‘qitish va joriy etilgan yechimlarni qo‘llab-quvvatlashgacha — yechimning butun hayotiy sikli davomida muvofiqlashtirilgan yondashuvni ta’minlaymiz.')),
            ('p', X('Our objective is not simply to introduce new technology.', 'Наша цель — не просто внедрить новую технологию.', 'Maqsadimiz shunchaki yangi texnologiyani joriy etish emas.')),
            ('p', X('It is to help customers modernize in a practical and sustainable way — preserving what works, integrating what is new, and building for what comes next.',
                    'Мы помогаем заказчикам модернизироваться практично и устойчиво — сохраняя то, что работает, интегрируя новое и создавая основу для будущего.',
                    'Bu — buyurtmachilarga amaliy va barqaror tarzda modernizatsiya qilishda yordam berish: ishlayotganini saqlash, yangisini integratsiya qilish va kelajak uchun asos yaratish.')),
        ]}),
        ('closing', {'style': 'statement', 'statement': BRAND_STATEMENT, 'lines': [
            X('From Technology to Operational Capability', 'От технологий — к операционным возможностям', 'Texnologiyadan — operatsion imkoniyatgacha'),
        ], 'buttons': [
            (EXPLORE_SOLUTIONS, 'solutions.html', 'primary-link'),
            (TRAINING, 'training.html', 'text-link'),
        ]}),
    ],
}
