from . import X, BRAND_STATEMENT, CONTACT_S3, FSR_SUPPORT

PAGE = {
    'slug': 'training.html',
    'title': X('Training & Knowledge Transfer', 'Обучение и передача знаний', 'O‘qitish va bilim almashish'),
    'image': 'technical-team.webp',
    'hero': {
        'title': X('Technology Becomes Capability Through People', 'Технологии становятся возможностями благодаря людям', 'Texnologiya odamlar orqali imkoniyatga aylanadi'),
        'lead': X('Advanced technology delivers its full value only when personnel have the knowledge, practical skills, and confidence required to use and support it effectively.',
                  'Передовые технологии раскрывают свою ценность полностью только тогда, когда у персонала есть знания, практические навыки и уверенность, необходимые для их эффективного использования и поддержки.',
                  'Ilg‘or texnologiya o‘z qiymatini faqat xodimlarda undan samarali foydalanish va uni qo‘llab-quvvatlash uchun zarur bilim, amaliy ko‘nikma va ishonch bo‘lgandagina to‘liq namoyon etadi.'),
    },
    'blocks': [
        ('continuation', {'items': [
            ('emphasis', X('For this reason, training and knowledge transfer are integral parts of the S3 approach.',
                           'Поэтому обучение и передача знаний — неотъемлемые части подхода S3.',
                           'Shu sababli o‘qitish va bilim uzatish S3 yondashuvining ajralmas qismlaridir.')),
            ('p', X('S3 provides structured training programs for the technologies and integrated solutions we deliver. Working in cooperation with our technology partners, we combine product expertise, systems knowledge, practical exercises, and operational experience to help customers develop sustainable internal capabilities.',
                    'S3 проводит структурированные программы обучения по поставляемым технологиям и интегрированным решениям. В сотрудничестве с технологическими партнёрами мы объединяем знание продуктов и систем, практические упражнения и операционный опыт, помогая заказчикам развивать устойчивые внутренние компетенции.',
                    'S3 o‘zi yetkazib beradigan texnologiyalar va integratsiyalashgan yechimlar bo‘yicha tizimli o‘quv dasturlarini o‘tkazadi. Texnologik hamkorlarimiz bilan hamkorlikda mahsulot bo‘yicha ekspertiza, tizimlar haqidagi bilim, amaliy mashg‘ulotlar va operatsion tajribani birlashtirib, buyurtmachilarga barqaror ichki salohiyatni rivojlantirishda yordam beramiz.')),
            ('p', X('Our objective extends beyond teaching personnel how to operate individual products.',
                    'Наша цель шире, чем научить персонал пользоваться отдельными продуктами.',
                    'Maqsadimiz xodimlarga alohida mahsulotlardan foydalanishni o‘rgatish bilan cheklanmaydi.')),
            ('p', X('We help customers develop the knowledge required to operate, administer, maintain, support, and transfer knowledge about the systems they use.',
                    'Мы помогаем заказчикам развивать знания, необходимые для эксплуатации, администрирования, обслуживания и поддержки используемых систем, а также для передачи этих знаний другим.',
                    'Biz buyurtmachilarga o‘zlari foydalanadigan tizimlardan foydalanish, ularni boshqarish, ularga xizmat ko‘rsatish, ularni qo‘llab-quvvatlash va ular haqidagi bilimlarni boshqalarga uzatish uchun zarur bilimlarni rivojlantirishda yordam beramiz.')),
        ]}),
        ('prose', {'title': X('Training Designed Around the Customer', 'Обучение, построенное вокруг заказчика', 'Buyurtmachiga moslashtirilgan o‘qitish'), 'soft': True, 'items': [
            ('p', X('Every organization has different responsibilities, existing knowledge, operational requirements, and technical environments.',
                    'У каждой организации свои обязанности, уровень знаний, операционные требования и техническая среда.',
                    'Har bir tashkilotning o‘z vazifalari, mavjud bilimlari, operatsion talablari va texnik muhiti bor.')),
            ('p', X('S3 therefore adapts training programs to the specific solution, customer requirements, and responsibilities of the personnel being trained.',
                    'Поэтому S3 адаптирует программы обучения к конкретному решению, требованиям заказчика и обязанностям обучаемого персонала.',
                    'Shu sababli S3 o‘quv dasturlarini muayyan yechimga, buyurtmachi talablariga va o‘qitilayotgan xodimlarning vazifalariga moslashtiradi.')),
            ('p', X('Training can combine:', 'Обучение может сочетать:', 'O‘qitish quyidagilarni birlashtirishi mumkin:')),
            ('list', [
                X('Classroom instruction', 'Занятия в учебном классе', 'Sinfxonadagi mashg‘ulotlar'),
                X('Instructor-led demonstrations', 'Демонстрации под руководством инструктора', 'Instruktor boshchiligidagi namoyishlar'),
                X('Hands-on equipment training', 'Практическую работу с оборудованием', 'Uskunalar bilan amaliy mashg‘ulotlar'),
                X('System configuration', 'Настройку систем', 'Tizimlarni sozlash'),
                X('Communications and network planning', 'Планирование связи и сетей', 'Aloqa va tarmoqlarni rejalashtirish'),
                X('Practical exercises', 'Практические упражнения', 'Amaliy mashqlar'),
                X('Operational scenarios', 'Операционные сценарии', 'Operatsion ssenariylar'),
                X('Troubleshooting exercises', 'Упражнения по устранению неисправностей', 'Nosozliklarni bartaraf etish bo‘yicha mashqlar'),
                X('Individual and group assignments', 'Индивидуальные и групповые задания', 'Yakka va guruh topshiriqlari'),
                X('Knowledge assessments', 'Проверку знаний', 'Bilimlarni baholash'),
                X('Train-the-Trainer activities', 'Занятия по подготовке инструкторов', 'Trenerlarni tayyorlash mashg‘ulotlari'),
            ]),
            ('p', X('Where appropriate, training is conducted using the customer\'s actual equipment and operational environment, allowing participants to develop practical experience directly relevant to the systems they will use.',
                    'При необходимости обучение проводится на реальном оборудовании и в операционной среде заказчика, что позволяет участникам получить практический опыт, непосредственно связанный с системами, которыми они будут пользоваться.',
                    'Zarur hollarda o‘qitish buyurtmachining haqiqiy uskunalari va operatsion muhitida o‘tkaziladi, bu esa ishtirokchilarga o‘zlari foydalanadigan tizimlarga bevosita tegishli amaliy tajriba orttirish imkonini beradi.')),
        ]}),
        ('details', {'rows': [
            {'title': X('Operator Training', 'Обучение операторов', 'Operatorlarni o‘qitish'),
             'subtitle': X('Building Confidence in Day-to-Day Operation', 'Уверенность в повседневной работе', 'Kundalik ishda ishonch hosil qilish'),
             'items': [
                ('p', X('Operator training is designed for personnel who will use deployed systems as part of their regular responsibilities.',
                        'Обучение операторов предназначено для персонала, который будет использовать развёрнутые системы в рамках своих повседневных обязанностей.',
                        'Operatorlarni o‘qitish joriy etilgan tizimlardan kundalik vazifalari doirasida foydalanadigan xodimlar uchun mo‘ljallangan.')),
                ('p', X('The objective is to develop the practical knowledge and skills required to operate equipment and applications correctly, efficiently, and confidently.',
                        'Цель — развить практические знания и навыки, необходимые для правильной, эффективной и уверенной работы с оборудованием и приложениями.',
                        'Maqsad — uskunalar va ilovalardan to‘g‘ri, samarali va ishonch bilan foydalanish uchun zarur amaliy bilim va ko‘nikmalarni rivojlantirish.')),
                ('p', X('Depending on the solution, training can cover equipment operation, communications procedures, user interfaces, information exchange, basic configuration, operational functions, and practical use of integrated systems.',
                        'В зависимости от решения обучение может охватывать работу с оборудованием, порядок ведения связи, пользовательские интерфейсы, обмен информацией, базовую настройку, операционные функции и практическое использование интегрированных систем.',
                        'Yechimga qarab o‘qitish uskunalardan foydalanish, aloqa tartibi, foydalanuvchi interfeyslari, axborot almashinuvi, asosiy sozlash, operatsion funksiyalar va integratsiyalashgan tizimlardan amaliy foydalanishni qamrab olishi mumkin.')),
                ('p', X('Hands-on exercises form an important part of the training, allowing participants to apply what they have learned in representative operational scenarios.',
                        'Важная часть обучения — практические упражнения, позволяющие участникам применять полученные знания в типовых операционных сценариях.',
                        'Amaliy mashqlar o‘qitishning muhim qismi bo‘lib, ishtirokchilarga o‘rganganlarini namunaviy operatsion ssenariylarda qo‘llash imkonini beradi.')),
             ]},
            {'title': X('Administrator Training', 'Обучение администраторов', 'Administratorlarni o‘qitish'),
             'subtitle': X('Developing System-Level Expertise', 'Экспертиза на уровне системы', 'Tizim darajasidagi ekspertizani rivojlantirish'),
             'items': [
                ('p', X('Administrator training is intended for personnel responsible for configuring, managing, and supporting deployed systems.',
                        'Обучение администраторов предназначено для персонала, отвечающего за настройку, управление и поддержку развёрнутых систем.',
                        'Administratorlarni o‘qitish joriy etilgan tizimlarni sozlash, boshqarish va qo‘llab-quvvatlash uchun mas’ul xodimlarga mo‘ljallangan.')),
                ('p', X('Training can cover areas such as:', 'Обучение может охватывать такие темы, как:', 'O‘qitish quyidagi yo‘nalishlarni qamrab olishi mumkin:')),
                ('list', [
                    X('System architecture', 'Архитектура системы', 'Tizim arxitekturasi'),
                    X('Configuration and administration', 'Настройка и администрирование', 'Sozlash va boshqarish'),
                    X('Communications and network planning', 'Планирование связи и сетей', 'Aloqa va tarmoqlarni rejalashtirish'),
                    X('User and system management', 'Управление пользователями и системой', 'Foydalanuvchilar va tizimni boshqarish'),
                    X('System deployment', 'Развёртывание системы', 'Tizimni joriy etish'),
                    X('Integration and connectivity', 'Интеграция и подключение', 'Integratsiya va ulanish'),
                    X('Monitoring', 'Мониторинг', 'Monitoring'),
                    X('Troubleshooting', 'Устранение неисправностей', 'Nosozliklarni bartaraf etish'),
                    X('Backup and recovery', 'Резервное копирование и восстановление', 'Zaxira nusxalash va tiklash'),
                    X('Configuration management', 'Управление конфигурацией', 'Konfiguratsiyani boshqarish'),
                    X('Operational support', 'Эксплуатационная поддержка', 'Operatsion qo‘llab-quvvatlash'),
                ]),
                ('p', X('The objective is to develop customer specialists capable of performing appropriate system-management tasks independently and supporting end users within their organization.',
                        'Цель — подготовить специалистов заказчика, способных самостоятельно выполнять задачи по управлению системой и поддерживать конечных пользователей внутри своей организации.',
                        'Maqsad — tizimni boshqarishga oid tegishli vazifalarni mustaqil bajara oladigan va o‘z tashkilotidagi oxirgi foydalanuvchilarni qo‘llab-quvvatlay oladigan buyurtmachi mutaxassislarini tayyorlash.')),
             ]},
            {'title': X('Technical & Maintenance Training', 'Техническое обучение и обучение обслуживанию', 'Texnik va xizmat ko‘rsatish bo‘yicha o‘qitish'),
             'subtitle': X('Building Local Technical Capability', 'Развитие местных технических компетенций', 'Mahalliy texnik salohiyatni rivojlantirish'),
             'items': [
                ('p', X('Technical and maintenance personnel require a deeper understanding of the technologies they support.',
                        'Техническому и обслуживающему персоналу необходимо более глубокое понимание технологий, которые он поддерживает.',
                        'Texnik va xizmat ko‘rsatuvchi xodimlar o‘zlari qo‘llab-quvvatlaydigan texnologiyalarni chuqurroq tushunishlari kerak.')),
                ('p', X('S3 can provide training focused on installation, configuration, diagnostics, preventive maintenance, troubleshooting, and technical support.',
                        'S3 проводит обучение по установке, настройке, диагностике, профилактическому обслуживанию, устранению неисправностей и технической поддержке.',
                        'S3 o‘rnatish, sozlash, diagnostika, profilaktik xizmat ko‘rsatish, nosozliklarni bartaraf etish va texnik yordamga yo‘naltirilgan o‘qitishni taqdim eta oladi.')),
                ('p', X('Programs are adapted to the level of maintenance and technical responsibility expected from customer personnel.',
                        'Программы адаптируются к уровню обслуживания и технической ответственности, ожидаемому от персонала заказчика.',
                        'Dasturlar buyurtmachi xodimlaridan kutilayotgan xizmat ko‘rsatish va texnik mas’uliyat darajasiga moslashtiriladi.')),
                ('p', X('Our goal is to strengthen local technical capability, reduce unnecessary dependence on external support, and help customers maintain the availability and effectiveness of deployed systems.',
                        'Наша цель — укрепить местные технические компетенции, снизить излишнюю зависимость от внешней поддержки и помочь заказчикам поддерживать готовность и эффективность развёрнутых систем.',
                        'Maqsadimiz — mahalliy texnik salohiyatni mustahkamlash, tashqi yordamga ortiqcha qaramlikni kamaytirish va buyurtmachilarga joriy etilgan tizimlarning shayligi va samaradorligini saqlashda yordam berish.')),
             ]},
            {'title': X('Train-the-Trainer (ToT)', 'Подготовка инструкторов (ToT)', 'Trenerlarni tayyorlash (ToT)'),
             'subtitle': X('Knowledge That Continues to Grow', 'Знания, которые продолжают расти', 'O‘sishda davom etadigan bilim'),
             'items': [
                ('p', X('Train-the-Trainer programs are an important part of S3\'s approach to sustainable capability development.',
                        'Программы подготовки инструкторов — важная часть подхода S3 к устойчивому развитию компетенций.',
                        'Trenerlarni tayyorlash dasturlari S3 ning barqaror salohiyatni rivojlantirishga yondashuvining muhim qismidir.')),
                ('p', X('Rather than limiting knowledge transfer to a single group of end users, ToT programs prepare selected customer personnel to share acquired knowledge and practical skills with other members of their organization.',
                        'Вместо того чтобы ограничивать передачу знаний одной группой конечных пользователей, программы ToT готовят отобранных сотрудников заказчика делиться полученными знаниями и практическими навыками с другими членами своей организации.',
                        'Bilim uzatishni bitta oxirgi foydalanuvchilar guruhi bilan cheklash o‘rniga, ToT dasturlari buyurtmachining tanlangan xodimlarini egallangan bilim va amaliy ko‘nikmalarni o‘z tashkilotining boshqa a’zolari bilan ulashishga tayyorlaydi.')),
                ('p', X('Participants develop both technical competence and the understanding required to support further internal training.',
                        'Участники развивают как техническую компетентность, так и понимание, необходимое для дальнейшего внутреннего обучения.',
                        'Ishtirokchilar ham texnik malakani, ham keyingi ichki o‘qitishni qo‘llab-quvvatlash uchun zarur tushunchani rivojlantiradi.')),
                ('p', X('This approach creates a multiplier effect:', 'Такой подход создаёт эффект мультипликатора:', 'Bu yondashuv multiplikator samarasini yaratadi:')),
                ('flow', [
                    X('International Expertise', 'Международная экспертиза', 'Xalqaro ekspertiza'),
                    X('Customer Instructors', 'Инструкторы заказчика', 'Buyurtmachi instruktorlari'),
                    X('Wider Organization', 'Вся организация', 'Butun tashkilot'),
                ]),
                ('p', X('By developing qualified internal instructors, customers can expand knowledge across their organization, support the introduction of new personnel, and retain expertise over the long term.',
                        'Подготовив квалифицированных внутренних инструкторов, заказчики могут распространять знания по всей организации, облегчать ввод в строй новых сотрудников и сохранять экспертизу в долгосрочной перспективе.',
                        'Malakali ichki instruktorlarni tayyorlash orqali buyurtmachilar bilimlarni butun tashkilot bo‘ylab kengaytirishi, yangi xodimlarni ishga kiritishni qo‘llab-quvvatlashi va ekspertizani uzoq muddat saqlab qolishi mumkin.')),
                ('p', X('For S3, successful training is not measured only by the number of people who attend a course. It is measured by the customer\'s ability to retain, apply, and continue developing the knowledge transferred.',
                        'Для S3 успех обучения измеряется не только числом людей, прошедших курс, но и способностью заказчика сохранять, применять и развивать переданные знания.',
                        'S3 uchun o‘qitishning muvaffaqiyati faqat kursda qatnashganlar soni bilan o‘lchanmaydi. U buyurtmachining uzatilgan bilimlarni saqlash, qo‘llash va rivojlantirishda davom etish qobiliyati bilan o‘lchanadi.')),
             ]},
        ]}),
        ('prose', {
            'title': X('Training in Practice', 'Обучение на практике', 'Amaliyotdagi o‘qitish'),
            'subtitle': X('Falcon III Train-the-Trainer Program — Uzbekistan', 'Программа подготовки инструкторов Falcon III — Узбекистан', 'Falcon III trenerlarni tayyorlash dasturi — O‘zbekiston'),
            'items': [
                ('p', X('S3, in cooperation with L3Harris Technologies and Digital Technologies (DTECH), successfully delivered an intensive Train-the-Trainer program for representatives of the Armed Forces of the Republic of Uzbekistan.',
                        'S3 совместно с L3Harris Technologies и Digital Technologies (DTECH) успешно провела интенсивную программу подготовки инструкторов для представителей Вооружённых Сил Республики Узбекистан.',
                        'S3 L3Harris Technologies va Digital Technologies (DTECH) bilan hamkorlikda O‘zbekiston Respublikasi Qurolli Kuchlari vakillari uchun intensiv trenerlarni tayyorlash dasturini muvaffaqiyatli o‘tkazdi.')),
                ('p', X('The program focused on planning radio communications and the operation of L3Harris Falcon III tactical radio systems.',
                        'Программа была посвящена планированию радиосвязи и эксплуатации тактических радиосистем L3Harris Falcon III.',
                        'Dastur radioaloqani rejalashtirish va L3Harris Falcon III taktik radiotizimlaridan foydalanishga bag‘ishlangan edi.')),
            ],
        }),
        ('facts', {'facts': [
            ('8', X('Weeks of training', 'Недель обучения', 'Hafta o‘qitish')),
            ('18', X('Participants', 'Участников', 'Ishtirokchi')),
            ('2', X('Training groups', 'Учебные группы', 'O‘quv guruhi')),
        ]}),
        ('cards', {'columns': 'two', 'soft': True, 'cards': [
            (X('8 Weeks of Training', '8 недель обучения', '8 hafta o‘qitish'), [
                X('The program was delivered in two consecutive four-week training sessions, with a total of 18 participants completing the training across two groups.',
                  'Программа прошла в формате двух последовательных четырёхнедельных сессий; в общей сложности обучение в двух группах завершили 18 участников.',
                  'Dastur ketma-ket ikkita to‘rt haftalik o‘quv sessiyasida o‘tkazildi; jami 18 nafar ishtirokchi ikki guruhda o‘qishni yakunladi.'),
                X('The extended format allowed participants to progress from fundamental concepts and equipment familiarization to communications planning and extensive hands-on work with the radio systems.',
                  'Расширенный формат позволил участникам пройти путь от базовых понятий и знакомства с оборудованием до планирования связи и обширной практической работы с радиосистемами.',
                  'Kengaytirilgan format ishtirokchilarga asosiy tushunchalar va uskunalar bilan tanishishdan aloqani rejalashtirish va radiotizimlar bilan keng amaliy ishlashgacha bo‘lgan yo‘lni bosib o‘tish imkonini berdi.'),
                X('Training combined theoretical instruction with practical activities, enabling participants to develop both an understanding of the underlying concepts and the practical skills required to apply them.',
                  'Обучение сочетало теоретические занятия с практикой, что позволило участникам как понять базовые принципы, так и освоить практические навыки их применения.',
                  'O‘qitish nazariy mashg‘ulotlarni amaliy faoliyat bilan uyg‘unlashtirdi va ishtirokchilarga asosiy tushunchalarni anglash bilan birga ularni qo‘llash uchun zarur amaliy ko‘nikmalarni egallash imkonini berdi.')]),
            (X('Train-the-Trainer Approach', 'Подход Train-the-Trainer', 'Trenerlarni tayyorlash yondashuvi'), [
                X('The program was designed as Train-the-Trainer (ToT).',
                  'Программа была построена по модели подготовки инструкторов (ToT).',
                  'Dastur trenerlarni tayyorlash (ToT) modeli asosida tuzilgan.'),
                X('The objective was not only to develop the knowledge and practical skills of the participants themselves, but also to prepare graduates to transfer the knowledge acquired during the program to other service personnel within their organization.',
                  'Цель состояла не только в развитии знаний и практических навыков самих участников, но и в подготовке выпускников к передаче полученных знаний другим военнослужащим своей организации.',
                  'Maqsad nafaqat ishtirokchilarning o‘z bilim va amaliy ko‘nikmalarini rivojlantirish, balki bitiruvchilarni dastur davomida olingan bilimlarni o‘z tashkilotidagi boshqa harbiy xizmatchilarga uzatishga tayyorlash edi.'),
                X('This approach supports the development of sustainable internal training capability and enables knowledge to continue spreading beyond the original group of participants.',
                  'Такой подход способствует созданию устойчивой внутренней системы обучения и позволяет знаниям распространяться за пределы первоначальной группы участников.',
                  'Bu yondashuv barqaror ichki o‘qitish salohiyatini rivojlantirishga xizmat qiladi va bilimlarning dastlabki ishtirokchilar guruhidan tashqariga tarqalishiga imkon beradi.')]),
            (X('Training Focus', 'Направления обучения', 'O‘qitish yo‘nalishlari'), [
                X('The program covered two principal areas:',
                  'Программа охватывала два основных направления:',
                  'Dastur ikkita asosiy yo‘nalishni qamrab oldi:'),
                X('<strong>Radio Communications Planning</strong> — development of the knowledge and practical understanding required to plan radio communications and prepare communications capabilities for operational use.',
                  '<strong>Планирование радиосвязи</strong> — развитие знаний и практического понимания, необходимых для планирования радиосвязи и подготовки средств связи к применению.',
                  '<strong>Radioaloqani rejalashtirish</strong> — radioaloqani rejalashtirish va aloqa vositalarini operatsion foydalanishga tayyorlash uchun zarur bilim va amaliy tushunchani rivojlantirish.'),
                X('<strong>Falcon III Radio Operation</strong> — practical training in the operation and use of L3Harris Falcon III tactical radio systems.',
                  '<strong>Работа с радиостанциями Falcon III</strong> — практическое обучение эксплуатации и использованию тактических радиосистем L3Harris Falcon III.',
                  '<strong>Falcon III radiostansiyalari bilan ishlash</strong> — L3Harris Falcon III taktik radiotizimlaridan foydalanish bo‘yicha amaliy o‘qitish.'),
                X('Hands-on activities formed a significant part of the program, allowing participants to apply theoretical knowledge directly to the equipment and reinforce their skills through practical exercises.',
                  'Значительную часть программы составляли практические занятия, позволившие участникам применять теоретические знания непосредственно на оборудовании и закреплять навыки в упражнениях.',
                  'Amaliy mashg‘ulotlar dasturning muhim qismini tashkil etdi va ishtirokchilarga nazariy bilimlarni bevosita uskunalarda qo‘llash hamda ko‘nikmalarini amaliy mashqlar orqali mustahkamlash imkonini berdi.')]),
            (X('Building Sustainable Capability', 'Создание устойчивых компетенций', 'Barqaror salohiyat yaratish'), [
                X('The completion of the program represents more than the training of 18 individual participants.',
                  'Завершение программы — это нечто большее, чем обучение 18 отдельных участников.',
                  'Dasturning yakunlanishi 18 nafar ishtirokchini o‘qitishdan ko‘ra kattaroq ahamiyatga ega.'),
                X('Through the Train-the-Trainer model, the knowledge transferred during the eight-week program can continue to be shared with additional service personnel, supporting the development of wider organizational capability.',
                  'Благодаря модели подготовки инструкторов знания, переданные за восемь недель программы, могут и дальше передаваться другим военнослужащим, способствуя развитию возможностей всей организации.',
                  'Trenerlarni tayyorlash modeli tufayli sakkiz haftalik dastur davomida uzatilgan bilimlar boshqa harbiy xizmatchilar bilan ham ulashilishda davom etib, butun tashkilot salohiyatini rivojlantirishga xizmat qiladi.'),
                X('For S3, this reflects one of the fundamental principles behind our training approach:',
                  'Для S3 это отражает один из основополагающих принципов нашего подхода к обучению:',
                  'S3 uchun bu o‘qitishga yondashuvimizning asosiy tamoyillaridan birini aks ettiradi:'),
                X('<strong>Transfer knowledge. Develop instructors. Build sustainable capability.</strong>',
                  '<strong>Передавать знания. Готовить инструкторов. Создавать устойчивые возможности.</strong>',
                  '<strong>Bilim uzatish. Instruktorlar tayyorlash. Barqaror salohiyat yaratish.</strong>')]),
        ]}),
        ('prose', {'title': X('Training Through Partnership', 'Обучение через партнёрство', 'Hamkorlik orqali o‘qitish'), 'items': [
            ('p', X('S3 training programs can combine several levels of expertise.',
                    'Программы обучения S3 могут сочетать несколько уровней экспертизы.',
                    'S3 o‘quv dasturlari bir necha darajadagi ekspertizani birlashtirishi mumkin.')),
            ('p', X('Our international technology partners contribute detailed product and system knowledge. Experienced instructors provide technical and practical expertise. S3 provides local coordination, customer engagement, integration knowledge, and continued support.',
                    'Наши международные технологические партнёры дают глубокие знания о продуктах и системах. Опытные инструкторы привносят техническую и практическую экспертизу. S3 обеспечивает местную координацию, взаимодействие с заказчиком, знания в области интеграции и дальнейшую поддержку.',
                    'Xalqaro texnologik hamkorlarimiz mahsulot va tizimlar haqida batafsil bilim beradi. Tajribali instruktorlar texnik va amaliy ekspertizani taqdim etadi. S3 esa mahalliy muvofiqlashtirish, buyurtmachi bilan ishlash, integratsiya bo‘yicha bilim va doimiy qo‘llab-quvvatlashni ta’minlaydi.')),
            ('p', X('This cooperative approach helps connect manufacturer expertise, systems integration knowledge, operational experience, and customer requirements within a single training program.',
                    'Такой совместный подход позволяет объединить экспертизу производителя, знания в области системной интеграции, операционный опыт и требования заказчика в рамках единой программы обучения.',
                    'Bu hamkorlikdagi yondashuv ishlab chiqaruvchi ekspertizasi, tizim integratsiyasi bo‘yicha bilim, operatsion tajriba va buyurtmachi talablarini yagona o‘quv dasturida birlashtirishga yordam beradi.')),
            ('p', X('Training can also be followed by continued technical assistance and Field Service Representative support, allowing participants to reinforce their knowledge while working with deployed systems.',
                    'После обучения может предоставляться постоянная техническая помощь и поддержка выездных технических специалистов (FSR), что позволяет участникам закреплять знания в ходе работы с развёрнутыми системами.',
                    'O‘qitishdan keyin doimiy texnik yordam va joylardagi texnik vakillar (FSR) ko‘magi ko‘rsatilishi mumkin, bu esa ishtirokchilarga joriy etilgan tizimlar bilan ishlash jarayonida bilimlarini mustahkamlash imkonini beradi.')),
        ]}),
        ('prose', {'title': X('From Training to Independent Capability', 'От обучения — к самостоятельности', 'O‘qitishdan — mustaqil salohiyatgacha'), 'soft': True, 'items': [
            ('p', X('Our long-term objective is not to make customers permanently dependent on external instructors.',
                    'Наша долгосрочная цель — не сделать заказчиков постоянно зависимыми от внешних инструкторов.',
                    'Uzoq muddatli maqsadimiz buyurtmachilarni tashqi instruktorlarga doimiy qaram qilib qo‘yish emas.')),
            ('p', X('We aim to develop customer personnel who can increasingly operate, administer, maintain, troubleshoot, and teach the systems within their areas of responsibility.',
                    'Мы стремимся подготовить персонал заказчика, который со временем сможет всё более самостоятельно эксплуатировать, администрировать, обслуживать системы в своей зоне ответственности, устранять неисправности и обучать других.',
                    'Biz o‘z mas’uliyat doirasidagi tizimlardan tobora mustaqil foydalana oladigan, ularni boshqara oladigan, ularga xizmat ko‘rsata oladigan, nosozliklarni bartaraf eta oladigan va boshqalarni o‘rgata oladigan buyurtmachi xodimlarini tayyorlashga intilamiz.')),
            ('p', X('Training, Train-the-Trainer programs, knowledge transfer, and ongoing technical support therefore form part of the same capability-development process.',
                    'Поэтому обучение, программы подготовки инструкторов, передача знаний и постоянная техническая поддержка — части единого процесса развития компетенций.',
                    'Shu sababli o‘qitish, trenerlarni tayyorlash dasturlari, bilim uzatish va doimiy texnik yordam salohiyatni rivojlantirishning yagona jarayoni tarkibiga kiradi.')),
            ('flow', [
                X('Learn', 'Изучить', 'O‘rganish'), X('Practice', 'Отработать', 'Mashq qilish'), X('Apply', 'Применить', 'Qo‘llash'),
                X('Share', 'Передать', 'Ulashish'), X('Sustain', 'Закрепить', 'Barqarorlashtirish'),
            ]),
        ]}),
        ('prose', {'title': X('Knowledge Is Part of the Solution', 'Знания — часть решения', 'Bilim — yechimning bir qismi'), 'items': [
            ('p', X('At S3, training is not treated as an optional activity added after equipment delivery.',
                    'В S3 обучение не считается необязательным дополнением к поставке оборудования.',
                    'S3 da o‘qitish uskunalar yetkazib berilgandan keyin qo‘shiladigan ixtiyoriy faoliyat sifatida qaralmaydi.')),
            ('emphasis', X('It is part of the solution.', 'Оно — часть решения.', 'U yechimning bir qismidir.')),
            ('p', X('By combining advanced technology with structured training, hands-on practice, Train-the-Trainer programs, knowledge transfer, and continued support, we help customers turn technology into sustainable operational capability.',
                    'Сочетая передовые технологии со структурированным обучением, практикой, программами подготовки инструкторов, передачей знаний и постоянной поддержкой, мы помогаем заказчикам превращать технологии в устойчивые операционные возможности.',
                    'Ilg‘or texnologiyalarni tizimli o‘qitish, amaliy mashg‘ulotlar, trenerlarni tayyorlash dasturlari, bilim uzatish va doimiy qo‘llab-quvvatlash bilan uyg‘unlashtirib, buyurtmachilarga texnologiyani barqaror operatsion imkoniyatga aylantirishda yordam beramiz.')),
        ]}),
        ('closing', {'statement': BRAND_STATEMENT, 'lines': [
            X('From Technology to Knowledge. From Knowledge to Capability.', 'От технологий — к знаниям. От знаний — к возможностям.', 'Texnologiyadan — bilimga. Bilimdan — imkoniyatga.'),
        ], 'buttons': [
            (FSR_SUPPORT, 'support.html', 'primary-link'),
            (CONTACT_S3, 'contact.html', 'text-link'),
        ]}),
    ],
}
